(() => {
  "use strict";
  const params=new URLSearchParams(location.search), token=params.get("token")||"", overlay=params.get("overlay")||"gravity";
  const suffix=`token=${encodeURIComponent(token)}&overlay=${encodeURIComponent(overlay)}`;
  const root=document.getElementById("gravity"); let revision=-1,busy=false,ready=false;
  const set=(id,value)=>{const node=document.getElementById(id);if(node)node.textContent=value;};
  function theme(palette={},effects={}){const map={bg:"bg",panel:"panel",panel_raised:"raised",border:"border",border_soft:"soft",accent:"accent",orange:"orange",text:"text",muted:"muted",dim:"dim",yellow:"yellow",red:"red"};for(const [key,css] of Object.entries(map)){const value=String(palette[key]||"");if(/^#[0-9a-f]{6}$/i.test(value))document.documentElement.style.setProperty(`--${css}`,value);}document.documentElement.style.setProperty("--scale",String(Number(effects.text_scale)||1));const opacity=Number(effects.opacity);document.body.style.opacity=String(Number.isFinite(opacity)?Math.max(.4,Math.min(1,opacity)):1);root.classList.toggle("no-crt",!effects.crt);root.classList.toggle("reduced-motion",Boolean(effects.reduced_motion));}
  function render(snapshot={}){theme(snapshot.theme,snapshot.effects);const data=snapshot.gravity||{},g=Number(data.g),threshold=Number(data.threshold)||3,severity=["warning","high","critical"].includes(data.severity)?data.severity:"warning";root.className=`gravity ${severity}${snapshot.effects?.crt?"":" no-crt"}${snapshot.effects?.reduced_motion?" reduced-motion":""}`;set("severity",severity.toUpperCase());set("body",String(data.body||"UNKNOWN BODY").toUpperCase());set("value",Number.isFinite(g)?g.toFixed(2):"—");set("detail",Number.isFinite(g)?`THRESHOLD ${threshold.toFixed(1)} G · DESCENT ENVELOPE REDUCED`:`THRESHOLD ${threshold.toFixed(1)} G`);document.getElementById("load-fill").style.setProperty("--load",`${Math.min(100,Math.max(0,(Number(data.ratio)||0)*50))}%`);}
  async function refresh(next){const response=await fetch(`/api/snapshot?${suffix}`,{cache:"no-store"});if(!response.ok)return;render(await response.json());await new Promise(resolve=>requestAnimationFrame(resolve));revision=next;try{await fetch(`/api/rendered?${suffix}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({revision:next})});if(!ready){ready=true;await fetch(`/api/ready?${suffix}`,{method:"POST",body:"{}"});}}catch(_){}}
  async function poll(){if(busy)return;busy=true;try{const response=await fetch(`/api/health?${suffix}`,{cache:"no-store"});if(response.ok){const next=Number((await response.json()).revision);if(Number.isFinite(next)&&next!==revision)await refresh(next);}}catch(_){}finally{busy=false;}}
  poll();setInterval(poll,220);
})();
