(() => {
  "use strict";
  const params=new URLSearchParams(location.search),token=params.get("token")||"",overlay=params.get("overlay")||"ground-target",suffix=`token=${encodeURIComponent(token)}&overlay=${encodeURIComponent(overlay)}`;
  const root=document.getElementById("ground");let revision=-1,busy=false,ready=false;
  const set=(id,value)=>{const node=document.getElementById(id);if(node)node.textContent=value;};
  const finite=value=>value!==null&&value!==undefined&&value!==""&&Number.isFinite(Number(value));
  function theme(palette={},effects={}){const map={bg:"bg",panel:"panel",panel_raised:"raised",border:"border",border_soft:"soft",accent:"accent",orange:"orange",text:"text",muted:"muted",dim:"dim",green:"green",yellow:"yellow",red:"red"};for(const [key,css] of Object.entries(map)){const value=String(palette[key]||"");if(/^#[0-9a-f]{6}$/i.test(value))document.documentElement.style.setProperty(`--${css}`,value);}document.documentElement.style.setProperty("--scale",String(Number(effects.text_scale)||1));root.classList.toggle("no-crt",!effects.crt);root.classList.toggle("reduced-motion",Boolean(effects.reduced_motion));}
  function render(snapshot={}){theme(snapshot.theme,snapshot.effects);const data=snapshot.navigation||{},bearing=Number(data.bearing),delta=Number(data.heading_delta),heading=Number(data.heading);set("body-name",String(data.body||"SURFACE FIX").toUpperCase());set("direction",String(data.direction||"HEADING N/A").toUpperCase());set("distance",data.distance_label||"—");set("bearing",finite(bearing)?`BEARING ${bearing.toFixed(0).padStart(3,"0")}°`:"BEARING —");set("target",finite(data.target_lat)&&finite(data.target_lon)?`TARGET ${Number(data.target_lat).toFixed(5)}, ${Number(data.target_lon).toFixed(5)}`:"TARGET —");set("turn-value",finite(delta)?`${delta<0?"L":"R"} ${Math.abs(delta).toFixed(0)}°`:"—");set("coordinates",finite(data.current_lat)&&finite(data.current_lon)?`${Number(data.current_lat).toFixed(5)}, ${Number(data.current_lon).toFixed(5)}${finite(heading)?` · HDG ${heading.toFixed(0)}°`:""}`:"POSITION PENDING");document.getElementById("needle").style.setProperty("--needle",`${finite(delta)?delta:0}deg`);const fill=document.getElementById("turn-fill"),amount=finite(delta)?Math.min(50,Math.abs(delta)/180*50):0;fill.style.setProperty("--turn",`${amount}%`);fill.style.setProperty("--turn-transform",finite(delta)&&delta<0?"scaleX(-1)":"none");}
  async function refresh(next){const response=await fetch(`/api/snapshot?${suffix}`,{cache:"no-store"});if(!response.ok)return;render(await response.json());await new Promise(resolve=>requestAnimationFrame(resolve));revision=next;try{await fetch(`/api/rendered?${suffix}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({revision:next})});if(!ready){ready=true;await fetch(`/api/ready?${suffix}`,{method:"POST",body:"{}"});}}catch(_){}}
  async function poll(){if(busy)return;busy=true;try{const response=await fetch(`/api/health?${suffix}`,{cache:"no-store"});if(response.ok){const next=Number((await response.json()).revision);if(Number.isFinite(next)&&next!==revision)await refresh(next);}}catch(_){}finally{busy=false;}}
  poll();setInterval(poll,180);
})();
