(() => {
  "use strict";
  const params=new URLSearchParams(location.search),token=params.get("token")||"",overlay=params.get("overlay")||"ground-target";
  const root=document.getElementById("ground");
  const set=(id,value)=>{const node=document.getElementById(id);if(node)node.textContent=value;};
  const finite=value=>value!==null&&value!==undefined&&value!==""&&Number.isFinite(Number(value));
  function render(snapshot={}){VoidCompassOverlay.applyTheme(root,snapshot.theme,snapshot.effects);const data=snapshot.navigation||{},bearing=finite(data.bearing)?Number(data.bearing):null,delta=finite(data.heading_delta)?Number(data.heading_delta):null,heading=finite(data.heading)?Number(data.heading):null;set("body-name",String(data.target_label||data.body||"SURFACE FIX").toUpperCase());set("direction",String(data.direction||"HEADING N/A").toUpperCase());set("distance",data.distance_label||"—");set("bearing",finite(bearing)?`BEARING ${bearing.toFixed(0).padStart(3,"0")}°`:"BEARING —");set("target",finite(data.target_lat)&&finite(data.target_lon)?`TARGET ${Number(data.target_lat).toFixed(5)}, ${Number(data.target_lon).toFixed(5)}`:"TARGET —");set("turn-value",finite(delta)?Math.abs(delta)<=2?"AHEAD":`${delta<0?"L":"R"} ${Math.abs(delta).toFixed(0)}°`:"—");set("coordinates",finite(data.current_lat)&&finite(data.current_lon)?`${Number(data.current_lat).toFixed(5)}, ${Number(data.current_lon).toFixed(5)}${finite(heading)?` · HDG ${heading.toFixed(0)}°`:""}`:"POSITION PENDING");document.getElementById("needle").style.setProperty("--needle",`${finite(delta)?delta:0}deg`);const fill=document.getElementById("turn-fill"),amount=finite(delta)?Math.min(50,Math.abs(delta)/180*50):0;fill.style.setProperty("--turn",`${amount}%`);fill.style.setProperty("--turn-transform",finite(delta)&&delta<0?"scaleX(-1)":"none");}
  VoidCompassOverlay.startPolling({token, overlay, render, interval: 180});
})();
