"""Compatibility exports for the canonical cockpit-overlay registry."""

from voidcompass.core.overlay_registry import (
    DEFAULT_POSITIONS,
    DEFAULT_SIZES,
    HTML_OVERLAY_SPECS,
    OVERLAY_CARD_LABELS,
    OVERLAY_ENABLE_DEFAULTS,
    OVERLAY_ENABLE_KEYS,
    OVERLAY_HOTKEY_SPECS,
    OVERLAY_LABELS,
    OVERLAY_POSITION_SPECS,
    OVERLAY_SPECS,
    OVERLAY_SPEC_BY_ATTR,
)

__all__ = [
    "DEFAULT_POSITIONS", "DEFAULT_SIZES", "HTML_OVERLAY_SPECS",
    "OVERLAY_CARD_LABELS", "OVERLAY_ENABLE_DEFAULTS", "OVERLAY_ENABLE_KEYS",
    "OVERLAY_HOTKEY_SPECS", "OVERLAY_LABELS", "OVERLAY_POSITION_SPECS",
    "OVERLAY_SPECS", "OVERLAY_SPEC_BY_ATTR",
]
