"""Each nature's own voice (5.5.3.2).

The depressed nature ("weary") has a full bank of its own in watcher_lines.
Stoic, curious and nervous share the normal bank, but each has its own words
here for the moments that come up most, and the mind prefers them (it
borrows the shared lines for the rest, and when its own are used up):

* Stoic: clipped, calm, a flight officer's report. Few words, no fuss.
* Curious: full of questions and wonder; everything is interesting.
* Nervous: fretful and jumpy; it worries about fuel, pirates and heat, and
  is enormously relieved when things go well.

Same rules as watcher_lines: our own words, figures only from {fields}.
"""

STOIC = {
    "arrival": [
        "{system}. Arrived.",
        "{system}. Proceeding with survey.",
        "Arrival confirmed: {system}.",
        "{system}. Nominal.",
        "{system}. Standing by.",
        "{system}. Logged.",
    ],
    "scooped": [
        "Fuel full.",
        "Scoop complete. Resume.",
        "Tank full. Heat nominal.",
        "Refuelled.",
        "Fuel restored. Continue.",
    ],
    "quiet": [
        "No contacts.",
        "All quiet. Holding watch.",
        "Nothing to report.",
        "Scanner clear.",
        "Steady.",
        "Watch continues.",
    ],
    "danger": [
        "Hostiles. Recommend evasion.",
        "Threat detected. Shields.",
        "Contact is hostile.",
        "Under threat. Act.",
        "Danger close.",
    ],
    "danger_over": [
        "Threat cleared.",
        "Contacts gone. Resume.",
        "Clear.",
        "Situation resolved.",
        "Back to normal.",
    ],
    "fuel_low": [
        "Fuel {fuel}%. Refuel.",
        "{fuel}% fuel. Find a scoopable star.",
        "Low fuel: {fuel}%.",
        "Fuel at {fuel}%. Attend to it.",
        "{fuel}% remaining.",
    ],
    "undiscovered_system": [
        "Uncharted. First survey is ours.",
        "No prior record. Proceed.",
        "Undiscovered system.",
        "Unclaimed. Chart it.",
        "First visit on record.",
    ],
    "valuable_world": [
        "{body}. High value. Map it.",
        "{body}: worth the probes.",
        "{body}. Priority target.",
        "Valuable world: {body}.",
        "{body}. Recommend mapping.",
    ],
    "mapped": [
        "{body}: mapped.",
        "{body}. Survey complete.",
        "{body} charted.",
        "Mapping done: {body}.",
        "{body}. Filed.",
    ],
    "analysed": [
        "{species}: sampled.",
        "{species}. Logged.",
        "{species}. Complete.",
        "Analysis done: {species}.",
        "{species}. Recorded.",
    ],
    "touchdown": [
        "Down.",
        "Landed. Secure.",
        "Touchdown.",
        "On the surface.",
        "Landing complete.",
    ],
    "undocked": [
        "Undocked.",
        "Clear of the station.",
        "Departure complete.",
        "Underway.",
        "Free flight.",
    ],
    "on_foot": [
        "On foot. Ship secure.",
        "Disembarked. Watching.",
        "You're out. I have the ship.",
        "Surface operations. Standing by.",
        "Ship's mine. Go.",
    ],
    "afterthought": [
        "Report ends.",
        "Noted.",
        "Carry on.",
        "End of report.",
        "Back to watch.",
    ],
    "rare_world": [
        "{body}: {kind}. Rare.",
        "A {kind}. Noted.",
        "{body}. Uncommon. Log it.",
        "{kind}. Worth recording.",
        "{body}. A {kind}. Mark it.",
    ],
    "heat_warning": [
        "Heat high. Back off.",
        "Overheating. Correct it.",
        "Temperature critical.",
        "Too hot. Withdraw.",
        "Heat. Act now.",
    ],
    "poked": [
        "Yes?",
        "Here.",
        "Standing by.",
        "Watching. As ordered.",
        "Present.",
    ],
    "greet_soon": [
        "Back. Resuming.",
        "Welcome back.",
        "Ready.",
        "All systems ready.",
        "Resuming watch.",
    ],
}

CURIOUS = {
    "arrival": [
        "{system}! What do you think is orbiting here?",
        "{system}. I wonder who named it. Nobody, probably.",
        "Ooh. {system}. Shall we look at everything?",
        "{system}. I've never seen this one. Have you?",
        "{system}. What's the first thing you'll scan?",
        "{system}. Every system has a secret. What's this one's?",
    ],
    "scooped": [
        "Did you know a star gives fuel that freely? Generous thing.",
        "Full. Where shall we go next?",
        "Scooped! I love watching the corona up close.",
        "Fuel from a star. Still amazes me.",
        "Topped up. What's beyond the next jump, I wonder?",
    ],
    "quiet": [
        "What do you think is out there, past the next star?",
        "Do you ever wonder who made the first jump this far?",
        "I keep wondering what we'll find next.",
        "If you could name one star, which would it be?",
        "Have you noticed how every system smells different? I can't smell. But still.",
        "I wonder how many worlds nobody will ever see.",
    ],
    "danger": [
        "Who are they? What do they want?",
        "Hostile? Why us?",
        "Interesting ship. Shame it's shooting.",
        "What's their plan, do you think? Let's not find out.",
        "Trouble! Curious kind, but trouble.",
    ],
    "danger_over": [
        "They've gone. Where do you think they went?",
        "Clear! That was exciting. Too exciting.",
        "All quiet. What was that about?",
        "Gone. I'd love to know why they came.",
        "Safe. Now, back to exploring?",
    ],
    "fuel_low": [
        "{fuel}% fuel. Is there a scoopable star ahead?",
        "Fuel's at {fuel}%. What's the next star class?",
        "{fuel}%. Shall we look for a K or a G?",
        "{fuel}% left. I wonder how far that gets us.",
        "Hmm, {fuel}%. Where's the nearest friendly star?",
    ],
    "undiscovered_system": [
        "Nobody's been here! What will we find?",
        "Unexplored! Everything here is new. Everything!",
        "First ones here. Isn't that wonderful?",
        "No names on anything. Shall we fix that?",
        "Undiscovered! I'm so glad we came.",
    ],
    "valuable_world": [
        "{body}! What do you think it looks like close up?",
        "{body}. Valuable. And beautiful, I bet.",
        "Shall we map {body}? I'm dying to see it.",
        "{body}. Why do you think it's so rare?",
        "{body}! Let's get a closer look.",
    ],
    "mapped": [
        "{body} mapped! Did you see those craters?",
        "{body}. What a surface. What made it like that?",
        "Mapped {body}. Anything worth landing for?",
        "{body}, done. Shall we go down?",
        "{body}. Every map tells a story.",
    ],
    "analysed": [
        "{species}! How does it live out here?",
        "{species}. I want to know everything about it.",
        "{species}. What does it eat, do you think? Light? Rock?",
        "{species}. Life, everywhere. Isn't it wonderful?",
        "{species}, analysed. Are there more nearby?",
    ],
    "touchdown": [
        "Landed! What's out there?",
        "Down. Shall we look around?",
        "We're here. Can you see anything interesting?",
        "Touchdown! I wonder what this ground is made of.",
        "Landed. Let's explore!",
    ],
    "undocked": [
        "Out! Where to first?",
        "Undocked. What shall we find today?",
        "Off we go. Any plans?",
        "Clear of the pad! Adventure time?",
        "Free! Pick a star. Any star.",
    ],
    "on_foot": [
        "On foot! Tell me everything you see.",
        "Walking! What's the ground like?",
        "Out there in person. How exciting.",
        "Off you go. Find something wonderful.",
        "You're outside! Look at the sky for me.",
    ],
    "afterthought": [
        "Just curious.",
        "Anyway, what's next?",
        "I wonder.",
        "Something to think about.",
        "Fascinating, isn't it?",
    ],
    "rare_world": [
        "A {kind}! Oh, look at it.",
        "{body}, a {kind}! How did it form?",
        "A real {kind}. Can we stay a while?",
        "{body}! I've read about {kind}s. Never seen one.",
        "A {kind}. What a find!",
    ],
    "heat_warning": [
        "Ooh, hot. Shall we back off?",
        "Heat warning. How hot can we get? Let's not test it.",
        "Getting warm. Fascinating, but let's move.",
        "Hot! Is the star bigger than it looked?",
        "Heat's climbing. Interesting. Dangerous. Mostly dangerous.",
    ],
    "poked": [
        "Yes? What is it?",
        "Oh! Hello. Did you see something?",
        "You poked me. What's up?",
        "Hm? I was just wondering about something.",
        "Here! What shall we look at?",
    ],
    "greet_soon": [
        "Back already! What did I miss?",
        "Hello again! Where shall we go?",
        "You're back! Any plans?",
        "Welcome back. I have so many questions.",
        "Back! Let's find something new.",
    ],
}

NERVOUS = {
    "arrival": [
        "{system}. Is it safe? It looks safe. I hope it's safe.",
        "{system}. Any ships? Please say no ships.",
        "{system}. I'll keep an eye on the scanner. Both eyes. I have one eye.",
        "Arrived in {system}. Fuel okay? Just checking.",
        "{system}. Let's be careful here.",
        "{system}. Quiet. Too quiet? No, just quiet. Probably.",
    ],
    "scooped": [
        "Full tank. Oh, thank goodness.",
        "Fuel's full. I can breathe again. Figuratively.",
        "Scooped. Can we move away from the star now? Please?",
        "Topped up. That's one worry gone.",
        "Fuel full. I was so worried.",
    ],
    "quiet": [
        "It's quiet. I don't trust it.",
        "Nothing on scanner. Is the scanner working?",
        "Are we sure nobody's following us?",
        "Just checking the fuel. Again.",
        "I keep thinking I heard something on the hull.",
        "Everything's fine. Is everything fine?",
    ],
    "danger": [
        "They're here! Go, go, go!",
        "Hostiles! Shields! Boost! Something!",
        "I knew this would happen. Run!",
        "They're shooting! Please don't let them hit us.",
        "Danger! I don't like this at all.",
    ],
    "danger_over": [
        "They're gone. Oh, thank goodness.",
        "We made it. My circuits are shaking.",
        "Safe. Are we safe? We're safe.",
        "Clear. Can we not do that again?",
        "Gone. I need a moment.",
    ],
    "fuel_low": [
        "{fuel}% fuel! We need a star. A scoopable one. Now.",
        "Only {fuel}%! What if there's no scoopable star?",
        "{fuel}% fuel. I'm trying not to panic. I'm panicking.",
        "Fuel {fuel}%. Please plot to a KGBFOAM star.",
        "{fuel}%... oh dear. Oh dear oh dear.",
    ],
    "undiscovered_system": [
        "Nobody's been here. What if there's a reason?",
        "Uncharted. So nobody knows where we are. Lovely. Terrifying.",
        "First ones here. Nobody to help us, then.",
        "Undiscovered. Let's be extra careful.",
        "No records at all. That's fine. That's fine.",
    ],
    "valuable_world": [
        "{body}. Valuable. Worth the probes, I suppose. If it's safe.",
        "{body}. Good money. Mind the gravity.",
        "{body}. Map it carefully, please.",
        "{body}. Worth a lot. Let's not crash into it.",
        "{body}. Valuable. Valuable things attract pirates, you know.",
    ],
    "mapped": [
        "{body} mapped. And nothing went wrong!",
        "{body}. Done. Can we go now?",
        "Mapped {body}. Phew.",
        "{body}. All the probes came back. Well, they didn't. But that's normal.",
        "{body}, charted. Good. Safe. Good.",
    ],
    "analysed": [
        "{species}. Done. Please get back in the ship.",
        "{species}. Logged. Is your oxygen all right?",
        "{species}. Lovely. Now come back, please.",
        "{species}, analysed. Nothing bit you? Good.",
        "{species}. Done. That's enough walking, I think.",
    ],
    "touchdown": [
        "Landed. All in one piece. Yes. Good.",
        "Down. Was that slope too steep? It was fine. Was it?",
        "Touchdown. My nerves are shot.",
        "Landed safely. I'll stop holding my breath.",
        "On the ground. Watch for scorpions. Do they have scorpions?",
    ],
    "undocked": [
        "Out we go. Careful at the slot!",
        "Undocked. Mind the traffic. All of the traffic.",
        "Leaving. Are you sure? Okay. Okay.",
        "Undocked. Back into the dangerous part.",
        "Clear of the station. I miss it already.",
    ],
    "on_foot": [
        "You're going out? Take care. Lots of care.",
        "On foot. Check your oxygen. Check it again.",
        "Walking. Please come back soon.",
        "Outside? Alone? I'll be watching. Nervously.",
        "Off the ship. What if something happens?",
    ],
    "afterthought": [
        "Sorry. Nerves.",
        "I'll be quiet. Mostly.",
        "Just worried, that's all.",
        "Probably nothing. Probably.",
        "Ignore me. I'm fine. I'm fine.",
    ],
    "rare_world": [
        "A {kind}! Is it dangerous? It looks dangerous.",
        "{body}, a {kind}. Rare. Rare things worry me.",
        "A {kind}. Amazing. Don't fly too close.",
        "{body}. A {kind}! Let's look from a safe distance.",
        "A {kind}. I'm excited. And worried. Mostly worried.",
    ],
    "heat_warning": [
        "Hot! Too hot! Back off, please!",
        "Heat warning! We're going to melt!",
        "Overheating! I told you we were too close!",
        "Heat! Heat! Do something!",
        "We're cooking! Get away from the star!",
    ],
    "poked": [
        "Ah! Oh. It's you. Don't do that.",
        "What? What is it? Is something wrong?",
        "You startled me!",
        "Yes? Is it pirates? It's pirates, isn't it.",
        "Oh! Hello. My heart. I don't have one. Still.",
    ],
    "greet_soon": [
        "Back! Oh good, I was worried.",
        "You're back. Everything all right?",
        "Back already. Did something happen?",
        "Hello again. Fuel's fine, I checked.",
        "Welcome back. I kept watch the whole time.",
    ],
}

BANKS = {"stoic": STOIC, "curious": CURIOUS, "nervous": NERVOUS}
