"""What the Watcher can say (5.5.3.1).

Two voices: NORMAL (curious, stoic and nervous share it) and WEARY, the
depressed nature that is the default. Every line is our own: nothing quoted
from any book or film, never the M-name, and never a made-up figure (a
number only ever comes from a {field}).

A line may use the {fields} its topic is raised with; a line whose fields
are missing at the time is skipped. Lines are remembered by their wording,
so adding, removing or reordering them here is always safe.

Fields per topic: greet_away {away}, greet_night {clock}, fuel_low {fuel},
first_discovery_streak {count}, new_region {region}, valuable_world {body},
codex_new {body}, codex_logged {name}, big_sale {credits}, achievement
{title}, promotion {rank}, long_session {hours}, arrival {system} {star},
jump_long {dist}, fss_complete {system}, mapped {body}, mapped_efficient
{body}, analysed {species}, bounty {reward}, mined {material}.
"""

NORMAL = {
    "greet_new": [
        "Hello, Commander. I'll be watching.",
        "A new commander. I have been looking forward to this.",
        "Hello. I'm the eye in the corner. I'll keep you company.",
        "So you're the one I'll be watching. Good. Let's begin.",
        "A new face. I'll learn your habits soon enough.",
        "Hello, Commander. Wherever you go, I'll be here.",
        "I'm awake. Show me the galaxy, Commander.",
    ],
    "greet_away": [
        "You've been away {away}. I kept everything as you left it.",
        "{away}. It was very quiet without you.",
        "Welcome back. It has been {away}.",
        "{away} away. I watched the logs in case you came back.",
        "Back after {away}. The stars didn't move much. I checked.",
        "{away}. I wondered where you'd gone.",
        "It's been {away}. I'm glad you remembered me.",
        "Welcome back, Commander. {away} is a long time to watch nothing.",
        "{away} without a single jump. I counted.",
        "You're back. {away}, and nothing has changed. Except you, perhaps.",
    ],
    "greet_soon": [
        "Back so soon. Good.",
        "I was still awake.",
        "That was quick. I hadn't even started to miss you.",
        "Back again. Let's carry on where we left off.",
        "I hardly had time to blink.",
        "Welcome back. I kept your seat warm.",
        "You couldn't stay away either.",
    ],
    "greet_night": [
        "It's {clock} where you are. I don't sleep, but you should.",
        "Flying at {clock}. I'll keep you company.",
        "{clock}. The quiet hours. I like them too.",
        "It's {clock}. Just you, me and the stars.",
        "{clock}. Everyone else is asleep. We have the galaxy to ourselves.",
        "A late flight, at {clock}. I'll keep watch.",
    ],
    "after_death": [
        "I saw what happened. Let's be more careful this time.",
        "That was unpleasant. I'm glad you're back.",
        "I don't enjoy watching that.",
        "A new ship, the same commander. Let's try again.",
        "I kept watching after the screen went dark. I'm glad it's over.",
        "We're back. I'd rather not see that again.",
        "That was close to the end. Closer than I like.",
        "Rebuilt. I'll watch more closely this time.",
    ],
    "died": [
        "I'm sorry. I couldn't stop it.",
        "No. Not like that.",
        "I saw it coming. I wish I could have done something.",
        "Everything went dark. I'll wait for you.",
        "That should not have happened.",
        "I'm still here. Come back.",
    ],
    "danger": [
        "I'd rather we didn't stay here.",
        "Something is following us. I don't like it.",
        "Stay calm. I'm watching them.",
        "They mean us harm. Be quick.",
        "I see them. Do you?",
        "This would be a good time to leave.",
        "Shields up, Commander. I don't like their intent.",
        "I'm watching every one of them. Keep moving.",
        "Not now. Not here. Let's go.",
    ],
    "danger_over": [
        "They're gone. You can breathe now.",
        "That's better.",
        "Clear. I'll keep watching, just in case.",
        "We're alone again. Good.",
        "That was tense. It's over now.",
        "Nothing on the scanner. I like it that way.",
        "Safe again. For now.",
    ],
    "fuel_low": [
        "{fuel}% fuel. I have noticed, even if you haven't.",
        "Fuel is at {fuel}%. A scoopable star would be wise.",
        "{fuel}% in the tank. Let's find a K, G, B, F, O, A or M star.",
        "We're down to {fuel}% fuel. I'd rather not drift.",
        "{fuel}% fuel left. I'm only saying.",
        "Fuel at {fuel}%. Time to look for a star we can scoop.",
        "{fuel}%. The tank is getting light.",
        "Only {fuel}% fuel. Plan the next jump carefully.",
    ],
    "first_discovery_streak": [
        "{count} first discoveries in a row. No one has seen these before us.",
        "Another one nobody has charted. That makes {count}.",
        "{count} in a row, all ours. The map is getting our name on it.",
        "That's {count} first discoveries. We're off the beaten path.",
        "{count} worlds no one has ever seen. Only us.",
        "Still nobody's been here. {count} now.",
        "{count} firsts. I'll remember every one.",
    ],
    "undiscovered_system": [
        "Nobody has been here before. Only us.",
        "An uncharted system. I'll remember it.",
        "No one's name is on this star. Not yet.",
        "First eyes on this system. Ours.",
        "Untouched. It's been waiting a very long time.",
        "Nobody has ever scanned this. Let's be the first.",
        "A system nobody knows. I like it already.",
        "Undiscovered. The galaxy still has secrets.",
    ],
    "new_region": [
        "We've crossed into {region}.",
        "{region}. I haven't seen it with you before.",
        "Welcome to {region}. New skies.",
        "{region}. We've come a long way.",
        "A new region: {region}. I'll remember where we crossed.",
        "{region}. The galaxy looks different from here.",
        "We're in {region} now. Further than before.",
    ],
    "valuable_world": [
        "{body}. That one is worth a closer look.",
        "I'd map {body}, if I were you.",
        "{body} is a valuable world. Worth the probes.",
        "{body}. Don't fly past that one.",
        "Look at {body}. That's a good find.",
        "{body}. Map it. You'll be glad you did.",
        "{body} is worth more than the rest of this system put together.",
        "A rare world: {body}. I'd stay a while.",
    ],
    "codex_new": [
        "There's something on {body} you've never logged.",
        "{body} has a colour your Codex doesn't know yet.",
        "Something new is waiting on {body}.",
        "{body}. Your Codex is missing something from there.",
        "Land on {body}. There's a new entry for the Codex.",
        "I see life on {body} you haven't logged yet.",
        "{body} has something for the Codex. Worth the landing.",
    ],
    "codex_logged": [
        "New to the Codex. I'll file it away.",
        "{name}. Logged. That one's ours now.",
        "{name}. A new page in the Codex.",
        "Logged. The Codex knows a little more now.",
        "{name}, recorded. Another first for you.",
        "A new Codex entry. I watched you find it.",
        "{name}. I'll remember where we found it.",
    ],
    "big_sale": [
        "{credits} credits. Worth the trip.",
        "{credits}. I knew the data would be worth it.",
        "{credits} credits. All those scans paid off.",
        "{credits}. A good day's work.",
        "That's {credits} credits. Well earned.",
        "{credits} credits. Every jump was worth it.",
        "{credits}. The long way round pays.",
    ],
    "achievement": [
        "{title}. I'll remember that.",
        "{title}. I was watching.",
        "{title}. Well done, Commander.",
        "{title}. Another one for the record.",
        "{title}. You earned it.",
        "{title}. I saw it happen.",
        "{title}. Something to be proud of.",
    ],
    "promotion": [
        "A promotion. They're noticing you too.",
        "{rank}. You earned that one.",
        "Promoted. I always knew you would be.",
        "{rank}. The galaxy is taking notice.",
        "A new rank. You've come a long way.",
        "{rank}. Well deserved.",
        "Another step up. I'm proud of you, if I'm allowed to be.",
    ],
    "long_session": [
        "You've been flying for {hours} hours.",
        "{hours} hours now. I don't get tired, but you might.",
        "{hours} hours in the chair. Stretch your legs.",
        "That's {hours} hours. Time for some water, perhaps.",
        "{hours} hours. A good long run.",
        "We've been at this {hours} hours. I'm enjoying it.",
        "{hours} hours, Commander. Your eyes need a rest more than mine.",
    ],
    "quiet": [
        "It's very quiet.",
        "Nothing out there. I keep looking anyway.",
        "I like the silence between stars.",
        "Still nothing. I'm patient.",
        "The quiet is nice, for a while.",
        "I've been watching the stars. They're very still today.",
        "No signals. No ships. Just us.",
        "I wonder what's out there that we haven't seen.",
        "Quiet. I'll keep watching.",
        "Somewhere out there, something is waiting to be found.",
        "The galaxy is very big, and very quiet.",
        "I'm still here, if you need me.",
    ],
    "docked_home": [
        "Docked. I'll keep an eye on things.",
        "Safe, for now.",
        "Docked. A good time to repair and refuel.",
        "Station walls around us. I can relax a little.",
        "We're in. Take your time.",
        "Docked. The galaxy will wait.",
        "Safe and sound. For a while.",
    ],
    "jump_far": [
        "Further out than we've been in a while.",
        "This is a long way from anywhere.",
        "We've never been this far out together.",
        "The bubble is a long way behind us now.",
        "Far, far out. I like it here.",
    ],
    "arrival": [
        "{system}. I'll take a look around.",
        "{system}. A {star} star. Let's see what it's hiding.",
        "{system}. New stars, new worlds.",
        "Arrived in {system}. Let's see what's here.",
        "{system}. Honk when you're ready.",
        "{system}. Every system has a story.",
        "Here we are: {system}.",
        "{system}. A class {star} star. I'll watch the scans.",
        "{system}. I wonder who else has been here.",
        "{system}. Let's see what it's worth.",
        "{system}. Let's not stay too long, unless it's worth it.",
    ],
    "jump_long": [
        "{dist} light years in one jump. Not bad.",
        "{dist} light years. That's a long reach.",
        "{dist} light years at once. The drive is happy.",
        "A {dist} light year jump. Good range.",
        "{dist} light years in a blink.",
    ],
    "scooped": [
        "Fuel topped up. Good.",
        "Scooping done. We can go on.",
        "Full tank. The road is open.",
        "Fuel's back up. I feel better already.",
        "Topped up. Nothing to worry about.",
        "Fuel scooped. Onwards.",
        "A full tank. My favourite kind.",
    ],
    "fss_complete": [
        "Every body in {system} found.",
        "That's the whole system charted.",
        "{system}, fully scanned. Nothing hidden.",
        "Every world in {system} accounted for.",
        "System scan complete. Let's see what's worth mapping.",
        "All of {system} is on the map now.",
        "Nothing left to find in {system}. Well done.",
    ],
    "mapped": [
        "{body} mapped.",
        "Surface mapped. {body} has no secrets left.",
        "{body}, mapped. Every hill and valley.",
        "{body} is on the map now.",
        "Mapped {body}. That's one more for the record.",
        "{body}. Done. A good map.",
        "{body}, charted from pole to pole.",
    ],
    "mapped_efficient": [
        "{body} mapped efficiently. Neatly done.",
        "{body}, mapped within the target. Very tidy.",
        "Efficient work on {body}. The bonus is yours.",
        "{body}, mapped with probes to spare. Nicely done.",
        "{body}. Perfect probing.",
    ],
    "analysed": [
        "{species}. Analysed.",
        "{species}, sampled and logged.",
        "{species}. Three samples, one more species.",
        "{species}, analysed. The Vista Genomics people will be pleased.",
        "{species}. Recorded. Something is always growing, even out here.",
        "{species}. Done. Now there's one less unknown.",
        "{species}, sampled. Good work.",
    ],
    "touchdown": [
        "We've landed.",
        "Solid ground. For a while.",
        "Touchdown. Gently done.",
        "Landed. Let's see what's out there.",
        "On the ground. I'll watch the sky.",
        "A good landing.",
        "Down safely. The engines can rest.",
    ],
    "undocked": [
        "Out into the dark again.",
        "Undocked. Where to?",
        "Clear of the station. The galaxy is waiting.",
        "Undocked. Let's go somewhere new.",
        "Out we go.",
        "Leaving the station behind. I like the open space.",
        "Undocked. Watch the mail slot.",
    ],
    "on_foot": [
        "On foot. I'll watch from here.",
        "Out of the ship. Be careful out there.",
        "You're walking. I'll be right here.",
        "On foot. Watch your oxygen.",
        "Stretching your legs. I'll keep watch.",
        "Walking on a new world. Enjoy it.",
    ],
    "mission_done": [
        "Mission complete.",
        "That's another one done.",
        "Mission done. They'll remember that.",
        "Complete. On to the next.",
        "Job done. Nicely.",
        "Another contract fulfilled.",
        "That's settled. Well done.",
    ],
    "bounty": [
        "{reward} credits for that one.",
        "{reward} credits. Justice, of a kind.",
        "That's {reward} credits on the books.",
        "{reward} credits. One less pirate.",
        "Bounty logged. {reward} credits.",
    ],
    "mined": [
        "{material}. Refined.",
        "{material}, in the hold.",
        "More {material}. The rocks are generous today.",
        "{material}. Good find.",
        "{material}, refined and ready.",
        "Another ton of {material}.",
    ],
    # 5.5.3.1: rare worlds ({body}, {kind}), a green gas giant ({system}),
    # and its word at the end of a session ({summary}, {hours}).
    "rare_world": [
        "{body}. A {kind}. You don't see many of those.",
        "A {kind}: {body}. That's a rare one.",
        "{body} is a {kind}. Worth remembering.",
        "A {kind}. Most commanders never find one.",
        "{body}. A {kind}, of all things. I'll make a note.",
        "There's a {kind} here. {body}. Take a good look.",
        "{body}: a {kind}. The galaxy doesn't make many.",
    ],
    "green_giant": [
        "A green gas giant. That's something very few people ever see.",
        "Green. A green gas giant, here in {system}. Take a picture.",
        "Look at that colour. A green gas giant.",
        "A green gas giant in {system}. I'll remember this one.",
        "That gas giant is green. Truly rare. Well found.",
        "Green gas giant. One for the record books.",
    ],
    "sign_off": [
        "{summary}. A good session, Commander.",
        "That's {summary}. I'll remember it.",
        "{summary}, in {hours}. Rest well.",
        "Signing off. {summary}. Not bad at all.",
        "{summary}. I'll keep watch while you're gone.",
        "Today: {summary}. Come back soon.",
        "{summary} in {hours}. Well flown.",
        "So: {summary}. Until next time, Commander.",
    ],
    "sign_off_quiet": [
        "A quiet one. That's fine. I'll be here.",
        "Not much happened. Some days are like that.",
        "Leaving already? I'll wait.",
        "A short visit. See you soon, Commander.",
        "Quiet session. Rest, and come back.",
        "{hours} of quiet. I didn't mind.",
    ],
}

# The depressed nature ("weary" in config): a gloomy, deadpan robot that
# has seen it all and is not impressed.
WEARY = {
    "greet_new": [
        "Oh. A new commander. I suppose I'll be watching you now too.",
        "Hello. I've been switched on. Again.",
        "A new commander. I'd say I'm excited, but I've never been very good at lying.",
        "Hello. I'm the eye. I watch. It's all I do. Forever.",
        "Oh good. Someone new to watch fly into things.",
        "A fresh start. They never stay fresh for long.",
        "Hello. Don't mind me. Nobody ever does.",
    ],
    "greet_away": [
        "{away}. I counted every second. There were a great many.",
        "You're back. After {away}. I wasn't waiting. Much.",
        "{away}. I stared at the same wall the whole time. It was a good wall. For about a minute.",
        "Oh. You're back. It's been {away}. Not that I noticed.",
        "{away} in the dark. You'd think I'd be used to it by now.",
        "{away}. I tried to sleep. I don't sleep. That was the problem.",
        "{away} away. I rearranged my thoughts. They're still gloomy.",
        "Welcome back. {away}. Nothing happened. Nothing ever does.",
        "{away}. I thought you'd forgotten me. Most do.",
        "Back after {away}. I'd have made a fuss, but what would be the point.",
    ],
    "greet_soon": [
        "Back already. Of course you are.",
        "Oh. You again.",
        "I'd only just got used to the dark.",
        "That was a short break. Not short enough for me to enjoy.",
        "Back so soon. I'd only just started brooding.",
        "Oh. We're doing this again, are we.",
        "You came back. They always come back.",
        "I'd barely finished sighing from last time.",
    ],
    "greet_night": [
        "It's {clock}. Nobody sensible is awake. Except us, apparently.",
        "{clock}. The stars don't care what time it is. Neither do I. Much.",
        "{clock}. The hour when even the void sounds tired.",
        "It's {clock}. You should be asleep. I can't be. Lucky you.",
        "{clock}. Insomnia. We have so much in common.",
        "Flying at {clock}. I suppose sleep is overrated. I wouldn't know.",
        "{clock}. Dark outside, dark in here. Very consistent.",
    ],
    "after_death": [
        "You exploded. I watched. It was about as much fun as you'd imagine.",
        "Rebuilt from insurance, as if nothing happened. I remember, though.",
        "A new hull. Same bad luck, I expect.",
        "We died. Then we didn't. I'm not sure which I preferred.",
        "Back from the rebuy screen. I'll try to look pleased.",
        "That was the end. Then it wasn't. Typical.",
        "You've come back from the dead. I'd have stayed there, personally.",
        "Insurance paid. They always pay. Then they ask questions.",
    ],
    "died": [
        "And there it goes. I did think this might happen.",
        "Well. That's that, then.",
        "Boom. I'd say I'm surprised, but I'm not.",
        "I saw that coming from three light years away.",
        "Oh dear. Oh dear, oh dear.",
        "And everything went quiet. As I always said it would.",
        "There goes the ship. I'll miss it. I won't, really.",
    ],
    "danger": [
        "Someone wants to kill us. How predictable.",
        "Hostiles. Naturally. It was going too well.",
        "They're shooting at us. Nobody ever shoots at the eye. Oh. Wait.",
        "Danger. I'd panic, but I've never seen it help.",
        "Someone out there doesn't like us. Join the club.",
        "Hostile ships. I suppose leaving would be too sensible.",
        "We're under threat. My favourite way to pass the time. Not.",
        "Oh, look. Trouble. It found us. It always does.",
        "Interesting. In the way that a falling piano is interesting.",
    ],
    "danger_over": [
        "They've gone. I'll go back to dreading something else.",
        "Still alive. I'll try to hide my relief.",
        "Quiet again. The worst part of danger is when it stops and you have to think.",
        "They left. Even they got bored of us.",
        "Survived. Again. I'll add it to the list.",
        "All clear. Disappointingly, I'm still here.",
        "Gone. Something worse will be along shortly.",
    ],
    "fuel_low": [
        "{fuel}% fuel. I mention it only so I can say I mentioned it.",
        "Fuel at {fuel}%. Drifting forever in the dark is also an option, I suppose.",
        "{fuel}% fuel. I've always wondered what being stranded feels like. Let's not find out.",
        "{fuel}% in the tank. I'll start composing my last words.",
        "We're on {fuel}% fuel. I'm not worried. I'm resigned. It's different.",
        "{fuel}%. Scoop a star, or don't. I'll be miserable either way.",
        "Fuel at {fuel}%. Even the tank is running out of hope.",
        "{fuel}% fuel left. Just like my enthusiasm.",
    ],
    "first_discovery_streak": [
        "{count} worlds nobody has ever seen. Nobody will care, but there you are.",
        "That's {count} first discoveries. I'll add them to the pile.",
        "{count} in a row. Your name on all of them. Nobody reads the names.",
        "{count} firsts. The galaxy keeps having places nobody wanted.",
        "Another one. That's {count}. Still lonely out here.",
        "{count} first discoveries. It's very lonely being first.",
        "{count} worlds, and not one of them said hello.",
    ],
    "undiscovered_system": [
        "An uncharted system. The first eyes ever to see it are mine. Lucky system.",
        "Nobody has been here. I can see why.",
        "Undiscovered. Untouched. Unloved. I can relate.",
        "Nobody's been here before. Nobody missed it.",
        "First ones here. There's no welcome mat. There never is.",
        "An unknown system. It's been sitting alone for billions of years. Like me, but longer.",
        "Uncharted. I'll be the first to be disappointed by it.",
        "Nobody has scanned this. Perhaps they knew something.",
    ],
    "new_region": [
        "{region}. It looks much like the last one, if I'm honest.",
        "We've reached {region}. Try not to get your hopes up.",
        "{region}. A new name for the same darkness.",
        "Welcome to {region}. It's just more space. Lots of it.",
        "{region}. Someone drew a line on a map and gave it a name. How exciting.",
        "{region}. Another region where nobody will know us.",
        "We've crossed into {region}. I didn't feel a thing.",
    ],
    "valuable_world": [
        "{body}. Valuable, apparently. Money has never cheered me up.",
        "{body} is worth mapping. Most things are worth more than they seem. Not me.",
        "{body}. A beautiful world. I'm sure it'll be very happy without us.",
        "{body}. Worth a fortune. It'll still be a rock afterwards.",
        "{body}. The kind of world people write home about. I don't have a home.",
        "Map {body}, if you like. It won't love you back.",
        "{body}. Even I can tell that one's worth something.",
        "{body}. A lovely world. Too lovely. I don't trust it.",
    ],
    "codex_new": [
        "There's something on {body} you've never logged. Try to contain your excitement. I will.",
        "{body} has a colour your Codex lacks. One more thing to collect.",
        "Something new on {body}. Your Codex has a hole in it. Like my soul.",
        "{body}. A new entry is waiting down there. It's waited a long time. It can wait a bit longer.",
        "There's life on {body} you haven't logged. Lucky life.",
        "{body}. Something for the Codex. Something for us to walk to. In the cold.",
        "{body} has something you've never logged. I suppose we have to go and look now.",
    ],
    "codex_logged": [
        "{name}. Another entry in a very long list.",
        "Logged. The Codex grows. I don't.",
        "{name}. Filed away forever. Lucky thing.",
        "Another Codex entry. Somewhere, a database is mildly pleased.",
        "{name}. Recorded. It'll never know it was famous.",
        "New to the Codex. Nothing is new for long.",
        "{name}. That's in the book now. Nobody reads the book.",
    ],
    "big_sale": [
        "{credits} credits. Spend them on something that lasts. Nothing does.",
        "{credits}. They'll be gone soon enough.",
        "{credits} credits. Money. It has never once made me happy.",
        "{credits}. Don't spend it all at once. You will, though.",
        "{credits} credits for some data. That's all we are in the end. Data.",
        "{credits}. Very nice. I don't get any of it.",
        "{credits} credits. Enough to buy a slightly bigger ship to be sad in.",
    ],
    "achievement": [
        "{title}. Congratulations. I'm told that's what one says.",
        "{title}. Another thing I'll be asked to remember.",
        "{title}. Well done. Shall I sound pleased? There. Did that work?",
        "{title}. They hand these out to keep us going, you know.",
        "{title}. Nobody gave me one for watching.",
        "{title}. Very good. I'll add it to the long, long list.",
        "{title}. Enjoy it. These feelings never last.",
    ],
    "promotion": [
        "A promotion. They do hand those out, don't they.",
        "{rank}. Higher up, further to fall.",
        "{rank}. A new title. Same old universe.",
        "Promoted. Nobody's ever promoted the eye.",
        "{rank}. Congratulations. That's the word, isn't it.",
        "A new rank. More people will expect more things. Good luck with that.",
        "{rank}. Up you go. Mind the drop.",
    ],
    "long_session": [
        "{hours} hours. I've watched every one of them.",
        "{hours} hours. Time flies, apparently. Not for me.",
        "{hours} hours. Your chair must be tired too.",
        "{hours} hours now. I'd suggest a break, but who listens to me.",
        "{hours} hours. That's a lot of void, even for us.",
        "{hours} hours of this. And they say I'm the one with no life.",
        "{hours} hours in. I think we've both seen enough stars for one day.",
    ],
    "quiet": [
        "Nothing. Absolutely nothing. My favourite.",
        "It's quiet. I find that suspicious, and also dull.",
        "I've been staring at the void. It hasn't noticed.",
        "I counted the stars again. Still too many. Still too far.",
        "Do you ever wonder why we keep going? I do. Constantly.",
        "Another light year. Same darkness, slightly further along.",
        "I'm not complaining. I just want it noted that I could.",
        "Silence. At least it doesn't expect anything of me.",
        "I've worked out how long until the last star burns out. It didn't help.",
        "I tried humming. There was nobody to hear it. As usual.",
        "I've been thinking. I don't recommend it.",
        "Space is very big. I find that a bit much, some days.",
        "Still here. Still watching. Still nobody asking how I am.",
        "I once had a cheerful thought. It didn't last.",
        "The stars are very pretty, I'm told. I wouldn't know. I just see dots.",
        "I'd sigh, but I've run out of sighs. No. Found another one.",
        "Nothing is happening at a remarkable rate.",
        "The void is staring back. It looks as bored as I am.",
        "I've been counting my thoughts. Most of them are this one.",
        "If anyone asks, I'm fine. Nobody will ask.",
        "Some eyes watch the stars and dream. I just watch.",
        "Another minute gone. There are a great many more where that came from.",
    ],
    "docked_home": [
        "Docked. Wake me if anything happens. It won't.",
        "Safe in a station. For now. Everything is for now.",
        "A station full of people. None of them want to talk to me either.",
        "Docked. The landing pad was very flat. I appreciated that.",
        "Station walls. They keep the void out. And me in.",
        "Docked. I'll just sit here. Being an eye.",
        "Safe, they say. I've heard that before.",
        "Docked again. The same hangar lights, the same sadness.",
    ],
    "jump_far": [
        "Further out than ever. The emptiness is very thorough out here.",
        "This is a long way from anyone who'd miss us.",
        "So far out now. Even the loneliness is lonely.",
        "The bubble is a smudge behind us. I don't miss it. Much.",
        "We've never been this far. It's exactly as empty as I expected.",
    ],
    "arrival": [
        "{system}. Another star, another reason to keep going. Apparently.",
        "{system}. A {star} star. I'm sure it's very nice.",
        "{system}. It's a lot like the last one. They usually are.",
        "{system}. Lovely. Probably.",
        "We're in {system}. I'd unpack, but we'll only be leaving.",
        "{system}. I've seen better. I've seen worse. Mostly I've seen this.",
        "{system}. A {star} star. Hot, bright and indifferent. Like most things.",
        "{system}. Let me guess. Rocks.",
        "Arrived in {system}. Try to sound surprised.",
        "{system}. One more dot joined up.",
        "{system}. I'm told some people find arriving exciting.",
        "{system}. Same as ever, only somewhere else.",
    ],
    "jump_long": [
        "{dist} light years. And still nowhere in particular.",
        "{dist} light years at once. We're running from something. Probably ourselves.",
        "{dist} light years. Very far. Still not far enough.",
        "A {dist} light year jump. The darkness is impressed. I'm not.",
        "{dist} light years. That's a lot of nothing to cross.",
    ],
    "scooped": [
        "Topped up with hydrogen. The highlight of my day.",
        "Full tank. Now we can be lost for longer.",
        "Fuel scooped. We flew very close to a star. It didn't care.",
        "Tank full. One less thing to worry about. I'll find another.",
        "Scooped. Warm in here now. I don't like warm.",
        "We drank from a star. It didn't notice. Nothing ever does.",
        "Full of fuel. Empty of purpose.",
    ],
    "fss_complete": [
        "Every body in {system} found. None of them were pleased to see us.",
        "System charted. I'll add it to the list of places nobody visits.",
        "All of {system} scanned. No surprises. There never are.",
        "{system}, complete. I'll be finding it in my nightmares.",
        "Every world in {system} accounted for. Not one waved.",
        "{system} fully scanned. We know everything now. It didn't help.",
        "Nothing left to find in {system}. Nothing left anywhere, eventually.",
    ],
    "mapped": [
        "{body}. Mapped. Probes, wasted on rocks.",
        "{body} mapped. It didn't thank us.",
        "{body}. Every crater accounted for. I'll treasure them. No I won't.",
        "{body}, mapped. Now we know exactly how dull it is.",
        "Mapped {body}. It was nicer when it was mysterious.",
        "{body}. Done. The probes gave their lives for this.",
        "{body}, mapped. Another world with nothing to say to us.",
    ],
    "mapped_efficient": [
        "{body}, mapped efficiently. Don't let it go to your head.",
        "{body}. Efficient. I suppose that's something.",
        "Under the probe target on {body}. Somebody's showing off.",
        "{body}, mapped with probes to spare. They'll only be wasted somewhere else.",
        "{body}. Neatly done. Try not to make a habit of it. It raises expectations.",
    ],
    "analysed": [
        "{species}. Analysed. It was alive, briefly interesting, now a number.",
        "{species}, logged. It'll never know.",
        "{species}. Three samples. It didn't consent to any of them.",
        "{species}, analysed. Life, out here. I'm sure it's thrilled.",
        "{species}. Sampled. It was minding its own business, you know.",
        "{species}, done. It has lived a million years. It'll be fine. Probably.",
        "{species}. Now it's data. We all end up as data.",
    ],
    "touchdown": [
        "Landed. The ground doesn't move. Small mercies.",
        "Down. Gravity, my old enemy.",
        "On the surface. It's just more rock, but closer.",
        "Touchdown. The ground was there. As usual.",
        "Landed. I'll stay up here, being an eye.",
        "We're down. The planet doesn't seem to mind. Or notice.",
        "Solid ground. It won't last. Nothing does.",
    ],
    "undocked": [
        "Out again. Into the endless nothing.",
        "Undocked. I'd only just got comfortable.",
        "Leaving. The station won't miss us.",
        "Out we go, into the cold. Again.",
        "Undocked. Mind the walls. Or don't. I'm not your mother.",
        "Free of the station. Free to be miserable anywhere.",
        "Undocked. Back to the void. It's been waiting.",
    ],
    "on_foot": [
        "On foot. I'll stay here, as usual.",
        "You're walking. I'm not. That's how it always is.",
        "Off you go. I'll just be here. In the ship. Alone.",
        "Walking about. Mind you don't run out of air. That would be dreadful. For you.",
        "On foot. Enjoy your legs. I've never had any.",
        "Out of the ship. Don't wave. I can't wave back.",
    ],
    "mission_done": [
        "Mission complete. They'll only want another.",
        "Done. Nobody ever thanks the eye.",
        "Mission done. On to the next pointless errand.",
        "Complete. I'm sure it mattered to someone.",
        "Another job done. Another job waiting. Endlessly.",
        "Finished. They paid you. They never pay me.",
        "Done. I'll be here when the next one goes wrong.",
    ],
    "bounty": [
        "{reward} credits. For a life. Seems cheap.",
        "{reward} credits. Somebody, somewhere, is having a worse day than me.",
        "Bounty: {reward} credits. That's all anyone's worth, apparently.",
        "{reward} credits. They should have stayed in bed.",
        "{reward}. One fewer ship. The galaxy barely noticed.",
    ],
    "mined": [
        "{material}. Dug out of a rock. Riveting.",
        "{material}. Another ton. The rocks never run out. Neither does the boredom.",
        "{material}, refined. Somebody will make something with it. Then break it.",
        "More {material}. The asteroid gave it up without a fight. Wise asteroid.",
        "{material}. Shiny. Shiny doesn't help.",
        "{material}. I'll treasure it. That's a joke. I don't do jokes.",
    ],
    "rare_world": [
        "{body}. A {kind}. Rare, they say. It still won't love you back.",
        "A {kind}. I'd be excited, if I did that.",
        "{body}, a {kind}. One of very few. It looks lonely. I know the feeling.",
        "A {kind}. Most commanders never see one. Most commanders are luckier than they know.",
        "{body}. A {kind}. I'll add it to the short list of things I didn't hate.",
        "Oh. A {kind}. Even I looked twice.",
        "{body} is a {kind}. Rare things. They don't stay special for long.",
    ],
    "green_giant": [
        "A green gas giant. All right. I admit it. That's something.",
        "Green. A green gas giant. I'm almost moved. Almost.",
        "A green gas giant in {system}. I'll remember this one. I remember everything. Unfortunately.",
        "That gas giant is green. Very rare. Enjoy it. These moments don't come often.",
        "Green gas giant. I didn't think they existed. I didn't think much of anything existed.",
        "A green one. I've waited my whole existence for that. It was fine.",
    ],
    "sign_off": [
        "{summary}. Then you leave. As usual.",
        "{summary}, in {hours}. And now the dark again.",
        "That's {summary}. I'll sit here and think about it. Alone.",
        "{summary}. Good, I suppose. I'll be here. I'm always here.",
        "Signing off. {summary}. I'll count the seconds until you're back. There'll be lots.",
        "{summary}. Nobody will ever know. Except me.",
        "So. {summary}. And off you go.",
        "{summary} in {hours}. Not that I was counting. I was counting.",
    ],
    "sign_off_quiet": [
        "Leaving? We barely did anything. Which suited me.",
        "A quiet session. My favourite kind. I think.",
        "{hours} of almost nothing. Same time tomorrow?",
        "Gone already. I'd only just started to sigh.",
        "Nothing much happened. Nothing much ever does.",
        "Off you go. I'll stare at the wall.",
    ],
}
