"""More for the Watcher to say (5.5.3.2), merged into watcher_lines.

A long session (two to four hours on Chatty) used up the smaller banks and
the Watcher fell quiet or came back to old lines, so every topic gets more
here, and the new ones about flying and walking about in Elite have their
own: the ship, supercruise, the SRV, settlements, taxis, fleet carriers,
station concourses, a world below, neutron boosts, heat and interdictions.

The same rules as watcher_lines: our own words (nothing quoted from any
book or film, never the M-name), every figure from a {field}, and
"[[typed|final]]" for a line that corrects itself as it types.

New fields: idle_ship {ship} {ship_name}; idle_supercruise {system};
idle_srv {body}; idle_settlement / settlement_seen {settlement};
idle_carrier / idle_station_foot {station} (and {suit}); idle_near_body
{body}; idle_on_foot {body} {suit}; carrier_jump {system}.
"""

MORE_NORMAL = {
    "greet_new": [
        "Hello, Commander. The Pilots Federation sent me your file. It was short.",
        "A new pilot. Let's see where you take us.",
        "Systems online. Eye open. I'm ready when you are.",
        "Hello. I'll watch the journal while you watch the stars.",
        "New commander, new log. I like a blank page.",
    ],
    "greet_away": [
        "{away}. The galaxy carried on without you. Rather rudely.",
        "Back after {away}. Your ship missed you. So did I.",
        "{away} gone. I kept the lights on.",
        "Welcome home, Commander. {away} is long enough to forget the controls. I'm sure you haven't.",
        "{away}. I read Galnet the whole time. You didn't miss much.",
        "There you are. {away}, and not a word.",
    ],
    "greet_soon": [
        "Back already? Good. I'd only just finished tidying the log.",
        "Couldn't keep away. I understand.",
        "Hello again. The stars are where you left them.",
        "Back in the chair. Let's go.",
        "Short break. Good. The black doesn't wait.",
        "You're back. I didn't even have time to wonder.",
    ],
    "greet_night": [
        "{clock}. Night flying. My favourite kind.",
        "It's {clock}. The bubble's asleep. We're not.",
        "Up at {clock}? Then let's make it worth it.",
        "{clock}. Quiet hours. Good for scanning.",
        "{clock}, and the stars still need charting.",
    ],
    "after_death": [
        "A new hull, fresh from the shipyard. Let's not scratch it.",
        "The rebuy screen. I've seen enough of it for one day.",
        "You're back in one piece. The ship is a different piece.",
        "Let's call that a lesson and move on.",
        "I logged what happened. I won't bring it up again. Probably.",
        "Back on your feet. Carefully this time.",
    ],
    "died": [
        "Hull gone. I'm still here. Come back.",
        "That's a rebuy. I'm sorry, Commander.",
        "I saw the canopy go. I'm sorry.",
        "No. Not now.",
        "The journal just went very quiet.",
    ],
    "danger": [
        "Weapons hot out there. Watch your shields.",
        "I don't like the look of them.",
        "Boost, Commander. Boost.",
        "They're not here to talk.",
        "Pips to shields might be wise.",
        "Hostile contact. I'm watching every move.",
        "Someone wants your cargo. Or your hull. Or both.",
        "Keep your eyes on the radar. I'll keep mine on you.",
    ],
    "danger_over": [
        "Shields recharging. Good.",
        "Clear skies again.",
        "They've broken off. Well flown.",
        "Quiet on the scanner. Let's keep it that way.",
        "We made it. Let's not do that again soon.",
        "All clear. You can breathe out.",
    ],
    "fuel_low": [
        "{fuel}% fuel. A scoopable star soon, please.",
        "Fuel at {fuel}%. Check the next jump's star class.",
        "{fuel}% left in the tank. I'm watching the gauge for you.",
        "Running light at {fuel}%. KGBFOAM, Commander.",
        "{fuel}% fuel. The Fuel Rats are wonderful, but let's not need them.",
        "We're at {fuel}%. Time to plot past a star we can drink from.",
    ],
    "first_discovery_streak": [
        "{count} first discoveries. Universal Cartographics will be busy.",
        "{count} untouched systems. Your name is spreading across the map.",
        "That's {count}. Nobody else has been this way.",
        "{count} firsts in a row. We're properly off the map now.",
        "{count} worlds with your name on them.",
        "{count}. The black keeps giving.",
    ],
    "undiscovered_system": [
        "No one's honked this star before us.",
        "Untagged. Ours to chart.",
        "No names on the system map. Let's change that.",
        "Undiscovered. The galaxy is still bigger than the Federation thinks.",
        "Clean slate. Every body here is a first.",
        "Nobody's been here. Not one.",
        "The first footprints in this system will be ours.",
    ],
    "new_region": [
        "{region}. A new patch of the galaxy on the map.",
        "Crossing into {region}. The Codex will have new pages here.",
        "{region}. Different stars, different life. Keep your eyes open.",
        "We've reached {region}. Well flown.",
        "{region}. I'll mark the crossing.",
        "Hello, {region}.",
    ],
    "valuable_world": [
        "{body}. Universal Cartographics will pay well for that one.",
        "A world worth the probes: {body}.",
        "{body}. Map it, and it'll pay for the trip.",
        "{body} looks valuable. Very valuable.",
        "Don't skip {body}. That one's worth the detour.",
        "{body}. I'd fire a few probes at that.",
    ],
    "rare_world": [
        "A {kind}. I've been hoping we'd see one.",
        "{body}. A {kind}. Not many of those in the catalogue.",
        "Rare: {body}, a {kind}.",
        "A {kind} right here. Take a screenshot.",
        "{body}. The Codex will want that {kind}.",
        "Look closer at {body}. A {kind}.",
    ],
    "green_giant": [
        "Green. Really green. A gas giant like that is something special.",
        "In {system}, a green gas giant. Remember this one.",
        "A green gas giant. Few commanders ever see one.",
        "That's a green gas giant. I'm almost speechless.",
        "Green, in {system}. Lovely.",
    ],
    "codex_new": [
        "Something on {body} is missing from your Codex.",
        "{body} has a new colour for you.",
        "A Codex gap, right there on {body}.",
        "There's life on {body} you haven't logged. Worth a landing.",
        "{body}. A new entry is waiting.",
    ],
    "codex_logged": [
        "{name}. Another page in the Codex.",
        "Logged: {name}.",
        "{name}. The Codex grows.",
        "Nice. {name} is in the book now.",
        "{name}. Recorded for the record.",
        "New Codex entry. Well found.",
        "{name}. Logged and dated.",
    ],
    "big_sale": [
        "{credits} credits. Universal Cartographics thanks you.",
        "{credits}. Worth every jump.",
        "{credits} credits. All that scanning, paid at last.",
        "{credits}. A good haul.",
        "{credits} credits banked. Time for an upgrade?",
        "{credits}. The black was generous.",
    ],
    "achievement": [
        "{title}. That's going in the record.",
        "{title}. Nicely done, Commander.",
        "{title}. I'll mark the moment.",
        "{title}. Earned, not given.",
        "{title}. I saw it happen, and I'm glad I did.",
    ],
    "promotion": [
        "{rank}. The Pilots Federation noticed.",
        "Promoted to {rank}. Well flown.",
        "{rank}. Your name climbs the list.",
        "{rank}. That took time. Well done.",
        "A new rank. Wear it well.",
    ],
    "long_session": [
        "{hours} hours. Maybe stretch a bit.",
        "{hours} hours in. Drink some water, Commander.",
        "{hours} hours. Long run. Good one.",
        "We've been flying {hours} hours. I'm still enjoying it.",
        "{hours} hours. Your eyes need a break more than the ship does.",
        "{hours} hours. Shall we find a station soon?",
    ],
    "quiet": [
        "Supercruise hum. I like it.",
        "Just the drive and the dark.",
        "I'm listening to the hull creak. It's company.",
        "Somewhere a beacon is blinking. Not for us.",
        "The scanner is empty. Peaceful.",
        "The galaxy is so still, out here.",
        "I'm watching the stars drift past.",
        "No signal sources. Just us.",
        "I like moments like this.",
        "A long silence. I don't mind it.",
        "The drive is humming nicely.",
        "Not a ship in sight.",
        "I've been thinking about where we'll go next.",
        "Quiet hands, quiet ship.",
    ],
    "docked_home": [
        "Docked. Refuel, repair, restock.",
        "The landing pad held. Good.",
        "Clamps on. We're safe.",
        "Docked. Maybe sell some data?",
        "Welcome to port, Commander.",
        "Station services are open. Take what you need.",
        "Docked. The ship can rest.",
    ],
    "jump_far": [
        "No traffic for hundreds of light years.",
        "The bubble is a memory now.",
        "Out here, every star is a stranger.",
        "Deep in the black.",
        "This far out, the silence has weight.",
        "Few pilots ever come this far.",
    ],
    "arrival": [
        "{system}. Honk when ready.",
        "Arrived: {system}.",
        "{system}. New star, fresh data.",
        "Dropping into {system}.",
        "{system}. Let's have a look.",
        "{system}. The journal has a new line.",
        "Welcome to {system}.",
        "{system}. The FSS is waiting.",
        "{system}. Another one for the map.",
        "{system}. I wonder what's in orbit here.",
        "{system}. Quiet, at first glance.",
        "In {system} now.",
    ],
    "jump_long": [
        "{dist} light years. The drive is earning its keep.",
        "A {dist} light year leap. Nicely plotted.",
        "{dist} light years in one go.",
        "{dist} light years. Good engineering.",
        "That jump covered {dist} light years.",
        "{dist} light years. It felt longer.",
        "{dist} light years. The FSD did well.",
    ],
    "scooped": [
        "Tank full. Nicely skimmed.",
        "Hydrogen, straight from the star.",
        "Scooping done. The heat's dropping.",
        "Full. Let's move away from that star.",
        "Good scoop. Not too hot.",
        "Fuel's sorted.",
        "Topped up. The road is long.",
        "That star gave us everything we needed.",
        "Fuel at full. Onwards.",
        "Tank's full. Mind the heat.",
        "Scooped. We can go anywhere now.",
        "Full tank. Peace of mind.",
    ],
    "fss_complete": [
        "{system}: every body found.",
        "Full spectrum done. Nothing escaped.",
        "The FSS is clear in {system}.",
        "All signals resolved in {system}.",
        "{system} is fully charted.",
        "Every last body in {system}. Thorough.",
        "System scan complete. Nicely done.",
        "{system} has nothing left to hide.",
        "That's the whole of {system}.",
        "Every world in {system} is on the map.",
    ],
    "mapped": [
        "{body}, mapped.",
        "Probes away, {body} done.",
        "{body}. The surface is on file.",
        "{body} is fully charted.",
        "{body} mapped. Good probing.",
        "Done with {body}.",
        "{body}. Every crater accounted for, and filed.",
        "{body} is on the surface charts now.",
        "Mapped {body}. Nice work.",
        "{body}: surface scan complete.",
    ],
    "mapped_efficient": [
        "{body}, under the probe target. Bonus earned.",
        "{body}. Efficient. Universal Cartographics likes that.",
        "Clean mapping on {body}.",
        "{body}: probes to spare, bonus in the bag.",
        "Neat work on {body}. Bonus secured.",
        "{body}. Not a probe wasted.",
        "Efficiency bonus on {body}. Well aimed.",
    ],
    "analysed": [
        "{species}. Logged for Vista Genomics.",
        "{species}. Done. One more for the catalogue.",
        "{species}, analysed. Good sampling.",
        "{species}. That's another one.",
        "{species}. The genetic sampler earned its keep.",
        "Sample complete: {species}.",
        "{species}, catalogued.",
        "{species}. It grows in such odd places.",
        "{species}. A good find.",
        "{species}. Three samples, done.",
    ],
    "touchdown": [
        "Landing gear down. Nicely done.",
        "Down on the surface.",
        "Touched down. Engines idle.",
        "Landed. Mind the slope.",
        "A gentle landing.",
        "We're down.",
        "The ship's feet are on the ground.",
        "Landed safely.",
        "Touchdown confirmed.",
        "Down. Let's look around.",
    ],
    "undocked": [
        "Clear of the pad.",
        "Out we go. Mind the mail slot.",
        "Undocked. Systems green.",
        "Leaving the station. Where to, Commander?",
        "Undocked. Space again.",
        "Free of the clamps.",
        "Out of the hangar.",
        "Undocked. The galaxy awaits.",
        "Lifting off the pad.",
        "Departure cleared.",
    ],
    "on_foot": [
        "Boots on the ground. I'll mind the ship.",
        "Out on foot. Keep an eye on your suit.",
        "Walking. I'll be here.",
        "Off the ship. Careful out there.",
        "On foot. Your oxygen's your business, but I'm watching too.",
        "You're out. I'll watch the horizon.",
        "Stepping out. Mind the gravity.",
        "Away from the ship. Stay safe.",
        "Out on the surface.",
        "Walking. Have fun.",
    ],
    "mission_done": [
        "Contract complete.",
        "Mission done. Payment's in.",
        "Another one finished. Well done.",
        "Done. They'll want you again.",
        "Job complete. Reputation up.",
        "Mission closed. Nice.",
        "That's the job done.",
        "Complete. On to the next one.",
    ],
    "bounty": [
        "{reward} credits. Justice served.",
        "Bounty: {reward} credits.",
        "{reward} credits on the voucher.",
        "{reward}. The system's a bit safer now.",
        "{reward} credits. Remember to cash it in.",
        "Another bounty: {reward} credits.",
        "{reward} credits. Good shooting.",
        "{reward}. Clean kill.",
    ],
    "mined": [
        "{material} in the refinery.",
        "{material}. One more ton.",
        "Refined: {material}.",
        "{material}. The hold fills up.",
        "{material}. Nice chunk.",
        "More {material}.",
        "{material}, processed.",
        "{material}. Good rock.",
    ],
    "sign_off": [
        "{summary}. That's a session to be proud of.",
        "{summary}. Rest well, Commander.",
        "{summary} in {hours}. I'll remember it.",
        "Logging off: {summary}.",
        "{summary}. Until next time.",
    ],
    "sign_off_quiet": [
        "See you next time, Commander.",
        "Goodbye for now.",
        "Rest. I'll keep watch.",
        "Short and quiet. Next time, then.",
        "Log closed. Fly safe.",
    ],
    "afterthought": [
        "Just saying.",
        "Anyway, back to it.",
        "Ignore me.",
        "I'll stop now.",
        "That's my thought for the day.",
        "Don't mind me.",
        "Back to watching.",
        "No need to reply.",
        "Moving on.",
        "I'll let that sit.",
        "There. Said it.",
        "Right. Carry on.",
    ],
    "idle_star": [
        "{A_star}. I could watch it all day. I do, in fact.",
        "{system}'s star burns steady.",
        "There's something calming about {a_star}.",
        "{A_star}. It's been burning since before anyone flew.",
        "{A_star} keeps us company.",
        "I like the colour of this {star}.",
        "{system}. {A_star}. Nothing to fear.",
        "The light from {a_star} is warm, in its way.",
    ],
    "idle_star_odd": [
        "{A_star}. Keep a safe distance, please.",
        "{A_star}. Strange, wonderful, and dangerous.",
        "I never get used to {a_star}.",
        "{system}'s {star}. Take a screenshot.",
        "{A_star}. Pilots come a long way to see one.",
        "Look at that {star}. Twisted light.",
        "{A_star}. Careful, Commander.",
        "{A_star}. The galaxy's oddities are its best part.",
    ],
    "idle_big_system": [
        "{count} bodies. Let's pick the best ones.",
        "{system} goes on and on. {count} bodies.",
        "So many bodies here. {count}. Something will be worth it.",
        "{count} bodies. A full day's work.",
        "{system} is crowded. {count} bodies.",
        "With {count} bodies, there's bound to be life somewhere.",
        "{count} worlds to sift through. Happily.",
        "{system}: {count} bodies and counting.",
    ],
    "idle_small_system": [
        "{system} is sparse. An easy survey.",
        "Hardly anything in {system}. Quick work.",
        "A lonely little system.",
        "{system}. Small, but it's ours.",
        "Not much orbiting here.",
        "Empty skies in {system}.",
        "A star and its silence.",
        "{system}. A short survey, then onwards.",
    ],
    "idle_far": [
        "{dist} light years from home. The Federation feels very far away.",
        "{dist} light years. The stars out here belong to nobody.",
        "{dist} light years out. Further than any trader dares.",
        "{dist} light years from Sol. Jameson Memorial is a long way back.",
        "{dist} light years. The silence is different this far.",
        "{dist} light years. Every jump takes us somewhere fewer have been.",
        "{dist} light years. I like it out here.",
        "{dist} light years from Earth. The black suits us.",
    ],
    "idle_home": [
        "{dist} light years from Sol. Traffic everywhere.",
        "The bubble, {dist} light years from Earth. Busy, busy.",
        "Home turf. {dist} light years from Sol.",
        "{dist} light years from Earth. Stations everywhere.",
        "So many beacons. We're near home.",
        "The bubble. Watch for pirates.",
        "Civilised space. {dist} light years from Sol.",
        "Back among people. {dist} light years from Earth.",
    ],
    "idle_recall": [
        "{Thing}. I keep going back to it.",
        "I've been replaying {thing}.",
        "{Thing}. Good memories already.",
        "That was a moment: {thing}.",
        "{Thing}. I'll keep it in the log.",
        "I liked {thing}.",
        "Still thinking about {thing}.",
    ],
    "idle_session": [
        "{jumps} jumps behind us today.",
        "{ly} light years. Good distance.",
        "{jumps} jumps. The FSD has earned a rest.",
        "{firsts} first discoveries so far today.",
        "{jumps} jumps and {ly} light years. A proper expedition.",
        "Today: {ly} light years of space.",
        "{jumps} jumps. Each one a little further.",
    ],
    "idle_night": [
        "{clock}. The quietest hour.",
        "{clock}. Night shift.",
        "It's {clock}. I hope you have coffee.",
        "{clock}. Even the stations are dim.",
        "{clock}. Late. I'm glad of the company.",
        "{clock}. Night flying suits you.",
    ],
    "idle_morning": [
        "{clock}. Morning flight. Nice.",
        "Good morning. {clock}.",
        "{clock}. Breakfast in the cockpit?",
        "Early, {clock}. The best time to fly.",
        "{clock}. A fresh start.",
        "{clock}. Morning, Commander.",
    ],
    "idle_docked": [
        "{station}. Shall we check the outfitting?",
        "Docked at {station}. No rush.",
        "{station}. Plenty of traffic.",
        "{station}. The market might be worth a look.",
        "{station}. Nice and safe.",
        "We're parked at {station}.",
        "{station}. Repairs done?",
        "{station}. A good place to rest.",
    ],
    "idle_landed": [
        "{body}. The view is good from here.",
        "Parked on {body}. Engines ticking.",
        "{body}. Still and quiet.",
        "On {body}. Want to take the SRV out?",
        "{body}. Not a bad place to sit.",
        "Grounded on {body}.",
        "{body}. Look at that horizon.",
        "Resting on {body}.",
    ],
    "idle_on_foot": [
        "Walking well. Watch your suit's oxygen.",
        "Out on {body}. Look up, now and then.",
        "Your {suit} is holding up.",
        "I'm minding the ship. Take as long as you need.",
        "Careful on {body}. The ground is uneven.",
        "Out on foot. I'll call if anything comes.",
        "Footsteps on {body}. Few have walked here.",
        "How's the {suit}? Snug, I hope.",
    ],
    "idle_music": [
        "{title}. Good flying music.",
        "{artist}. I like their style.",
        "{title}. Turn it up.",
        "This one's good. {title}.",
        "{title} again? I don't mind.",
        "{artist}, out here. Nice.",
    ],
    "idle_galnet": [
        "Galnet: {headline}. I'll keep an eye on that.",
        "Heard on Galnet: {headline}.",
        "Galnet's busy: {headline}.",
        "From the newsfeed: {headline}.",
        "{headline}. The bubble never sleeps.",
    ],
    "idle_self": [
        "{count} thoughts. I hope some were useful.",
        "{sessions} sessions. You're good company.",
        "{count} thoughts shared. Here's another: thank you.",
        "After {sessions} sessions, I know your habits.",
        "{count} thoughts. I'm getting chatty.",
    ],
    "idle_deaths": [
        "{times}. That's how many rebuys I've watched. Let's not add one.",
        "You've been destroyed {times}. You always come back.",
        "{times}. Every one of them is in the log.",
        "You've died {times}. Fly carefully.",
        "{times}. The insurers know your name.",
    ],
    # New: the ship, and what you're doing in it or out of it.
    "idle_ship": [
        "This {ship} has carried us well.",
        "The {ship} is running smoothly.",
        "{ship_name}. I like her name.",
        "I've been listening to the {ship}'s systems. All good.",
        "The {ship}. Good choice.",
        "{ship_name} is in fine shape.",
        "A good ship, the {ship}.",
        "I know every module on this {ship}.",
        "{ship_name}. A name the galaxy will know.",
        "The {ship} hums when it's happy. It's humming.",
        "Our {ship} has seen a lot of stars.",
        "{ship_name}. Ours.",
    ],
    "idle_supercruise": [
        "Supercruise through {system}. Nice view.",
        "Cruising in {system}. I'm watching the throttle.",
        "The drive is steady. {system} rolls by.",
        "{system}, at speed.",
        "Supercruise. Mind the time to destination.",
        "Cruising. Seven seconds out, remember.",
        "{system} looks peaceful from supercruise.",
        "Supercruise is the closest thing to flying through a dream.",
        "Coasting through {system}.",
        "Slow down near the target. That's the trick.",
        "We're cruising. I like the hum.",
        "{system}. The planets are drifting past.",
    ],
    "idle_srv": [
        "The SRV handles well.",
        "Out in the SRV. Mind the hills.",
        "Driving on {body}. Wheels down, spirits up.",
        "A bumpy ride on {body}.",
        "The SRV's turret is ready, just in case.",
        "Careful on the slopes. The SRV likes to tumble.",
        "Driving across {body}. Lovely.",
        "The SRV's scanner might find something.",
        "Off-road on {body}.",
        "Watch the SRV's hull.",
        "A good drive. Keep going.",
        "The ship is waiting. Take your time in the SRV.",
    ],
    "idle_settlement": [
        "{settlement}. Someone lives here.",
        "Near {settlement}. Watch for security.",
        "{settlement}. Lights on, somebody home.",
        "{settlement}. A place on the map with people in it.",
        "{settlement}. Want to land and look?",
        "{settlement}. Mind the no-fire zone.",
        "I can see {settlement} from here.",
        "{settlement}. A busy little place.",
        "{settlement}. I wonder what they make here.",
        "{settlement}. Friendly, I hope.",
        "{settlement}. Prefab domes and ambition.",
        "{settlement}. Plenty of work for a commander on foot.",
    ],
    "idle_taxi": [
        "Someone else is flying. Relax.",
        "A taxi ride. Enjoy the view.",
        "Apex is driving. Hold on.",
        "Let the pilot do the work.",
        "The passenger seat. A nice change.",
        "Sit back. I'll watch the route.",
        "Nobody asked me to drive.",
        "A taxi. Don't forget to say thank you.",
        "Just along for the ride.",
        "A smooth flight. Taxi pilots are better than they look.",
        "Riding with Apex. Let's see how they handle.",
        "We'll be there soon.",
    ],
    "idle_carrier": [
        "{station}. A carrier is a good home.",
        "Docked on {station}. Tritium levels all right?",
        "{station}. A home that moves.",
        "Carrier life. I like it.",
        "{station}. The deck crew is busy.",
        "On the carrier. Safe as anywhere.",
        "{station} is waiting for its next jump.",
        "{station}. A city that jumps.",
        "Docked at {station}. Shall we plot the next jump?",
        "The carrier deck. Quiet tonight.",
        "{station}. Our own little station.",
        "The carrier hums under us.",
    ],
    "idle_station_foot": [
        "Walking the concourse at {station}.",
        "{station}. Shops, bars, and missions.",
        "The concourse is busy at {station}.",
        "On foot in {station}. Check the mission board.",
        "{station}. The bartender might have something for you.",
        "A walk around {station}. Nice.",
        "{station}. Pioneer Supplies might have something useful.",
        "Your {suit} looks good in the concourse lights.",
        "{station}. Lots of people about.",
        "Stretching your legs at {station}.",
        "{station}. The ship is waiting in the hangar.",
        "I'll be in the hangar when you're done.",
    ],
    "idle_near_body": [
        "{body} below us.",
        "Orbiting {body}. Beautiful.",
        "{body}. Want to go down?",
        "Glide in to {body}?",
        "{body} fills the canopy.",
        "Approaching {body}. A lovely surface.",
        "{body}. Look at it turn.",
        "Near {body}. Gravity's pulling.",
        "{body}. Let's see what's on the ground.",
        "{body}. Every world looks different up close.",
        "In orbit around {body}.",
        "{body}. I'll keep an eye on the altitude.",
    ],
    "jet_boost": [
        "Neutron boost. Hold on.",
        "The jet cone. Supercharged.",
        "FSD supercharged. A big jump next.",
        "That's a good boost.",
        "Charged from the cone. Mind your FSD.",
        "The neutron highway. Here we go.",
        "Supercharged. Let's use it.",
        "The cone's done its work.",
        "Boosted. That's the fun bit.",
        "The jet cone. Exciting.",
    ],
    "heat_warning": [
        "Heat warning. Back off.",
        "We're running hot.",
        "Too hot. Pull away.",
        "Temperature climbing. Careful.",
        "Heat. Watch the modules.",
        "That's hot. Throttle back.",
        "A heat sink, maybe?",
        "We're cooking, Commander.",
        "Overheating. Let's cool down.",
        "Hot, hot, hot.",
    ],
    "interdiction_escaped": [
        "Escaped. Well flown.",
        "They couldn't hold us.",
        "Out of the interdiction. Nice.",
        "Broke free. Let's keep moving.",
        "Not today.",
        "Escape successful.",
        "Good evasion.",
        "They lost us.",
        "We're clear of their pull.",
        "Interdiction failed. Theirs, not ours.",
    ],
    "srv_launch": [
        "SRV deployed.",
        "Wheels on the ground.",
        "Time to drive.",
        "The SRV is out.",
        "Let's go exploring.",
        "SRV away. Have fun.",
        "Driving time.",
        "Down the ramp.",
        "SRV launched.",
        "Off you go.",
    ],
    "settlement_seen": [
        "{settlement} ahead.",
        "A settlement: {settlement}.",
        "{settlement}. People live out here.",
        "Approaching {settlement}.",
        "{settlement}. Let's see who's home.",
        "I see {settlement}.",
        "{settlement}. Careful with the no-fire zone.",
        "{settlement}. Mind their landing rules.",
        "{settlement}. Lights and domes.",
        "{settlement} on the scope.",
    ],
    "taxi_ride": [
        "A taxi. Let someone else fly.",
        "Apex booked.",
        "The passenger seat today.",
        "Taxi time.",
        "Off we go, the easy way.",
        "Enjoy the ride.",
        "Let's hope the driver's good.",
        "Taxi booked. Relax.",
        "Somebody else's ship for a change.",
        "A ride. Nice.",
    ],
    "carrier_jump": [
        "Carrier jump to {system}.",
        "The carrier jumped. {system} now.",
        "{system}. The whole station came with us.",
        "Carrier jump complete.",
        "{system}. Home moved again.",
        "Jumped the carrier to {system}.",
        "The carrier's in {system} now.",
        "{system}. A smooth carrier jump.",
        "The carrier arrived in {system}.",
        "{system}. We brought the station.",
    ],
}

MORE_WEARY = {
    "greet_new": [
        "A new commander. How exciting. For you.",
        "Hello. I'm your eye. I've been told to be positive. This is me being positive.",
        "Systems online. Mood offline.",
        "New commander, new disappointments. Let's begin.",
        "Oh. You're the new one. Right.",
    ],
    "greet_away": [
        "{away}. I stared at the same star the whole time. It didn't move. Neither did I.",
        "You were gone {away}. I counted the dust.",
        "{away}. I composed several poems about it. All of them were sad.",
        "Back after {away}. I'd started talking to the fuel gauge.",
        "{away}. I hope it was worth it. Mine wasn't.",
        "Oh. You remembered. After {away}.",
    ],
    "greet_soon": [
        "Back already. I'd only just started to feel abandoned.",
        "You again. I suppose that's nice. Is it? I can't tell.",
        "Couldn't stay away. Neither could I. I live here.",
        "Back so soon. The void missed you. I didn't. Much.",
        "Hello again. Nothing has improved.",
        "A short break. I spent it wishing I had a break.",
    ],
    "greet_night": [
        "{clock}. Even the stars look tired.",
        "{clock}. Flying instead of sleeping. Bold.",
        "It's {clock}. I'd yawn, but I don't have the parts.",
        "{clock}. The night is long. So am I.",
        "{clock}. Night flying. The galaxy won't notice.",
    ],
    "after_death": [
        "New ship. Same commander. Same eye. Same outcome, probably.",
        "The insurance clerk sends their regards.",
        "We're back. The universe gave us another go. It does that.",
        "A fresh hull. It'll get scratched. They all do.",
        "Rebuilt. I wasn't. I remember the whole thing.",
        "Back from the dead. Not my favourite trip.",
    ],
    "died": [
        "And the lights go out. As foretold.",
        "That's the end of that hull. I liked that hull. A bit.",
        "An explosion. Of course.",
        "There it goes. I'll start the paperwork.",
        "Gone. I'm still here. Lucky me.",
    ],
    "danger": [
        "They want to shoot us. Can't say I blame them.",
        "Hostiles. Lovely. Just what the day needed.",
        "I'd suggest leaving. Nobody listens to the eye.",
        "Shields up, for what it's worth.",
        "Here comes trouble. It usually does.",
        "They look angry. Join the queue.",
        "Boost, perhaps. Or explode. Your choice.",
        "This is going badly. Normally, then.",
    ],
    "danger_over": [
        "They left. Even pirates get bored of us.",
        "Survived. I'll update my expectations. Downward.",
        "Quiet again. The danger has gone to bother someone else.",
        "Still in one piece. Don't get used to it.",
        "We lived. Again. The pattern continues.",
        "Clear. I'll go back to worrying about other things.",
    ],
    "fuel_low": [
        "{fuel}% fuel. Drifting in the dark forever does sound restful.",
        "{fuel}% left. I've started planning my eulogy. It's short.",
        "Fuel at {fuel}%. A scoopable star would be nice. Nothing is ever nice.",
        "{fuel}%. Even the fuel is leaving us.",
        "{fuel}% fuel. I'm not saying worry. I'm saying I've seen this before.",
        "{fuel}% in the tank. The Fuel Rats will hear about this.",
    ],
    "first_discovery_streak": [
        "{count} first discoveries. Universal Cartographics will pay you, then forget you.",
        "{count} worlds nobody wanted. We found them anyway.",
        "{count}. All ours. All empty.",
        "That makes {count}. Someone has to discover the boring ones.",
        "{count} firsts. I've stopped being surprised. I was never surprised.",
        "{count}. The map gets bigger. We don't.",
    ],
    "undiscovered_system": [
        "Unexplored. For good reason, I expect.",
        "No one's ever come here. I'm starting to understand why.",
        "A blank system. Like my enthusiasm.",
        "Nobody's honked here. The silence was clearly intentional.",
        "First visitors. The star doesn't seem pleased.",
        "Undiscovered. Lonely. Relatable.",
        "Nobody's been here. We're the first to be disappointed.",
    ],
    "new_region": [
        "{region}. A line on a map. It doesn't feel any different.",
        "Welcome to {region}. Nobody's waiting.",
        "{region}. New name, same void.",
        "{region}. I'd say it's exciting. I won't, though.",
        "We've crossed into {region}. The darkness didn't notice.",
        "{region}. Another region of mostly nothing.",
    ],
    "valuable_world": [
        "{body}. Worth a fortune. It'll still be a rock tomorrow.",
        "{body}. Valuable. Unlike some of us.",
        "{body}. Map it. Get paid. Feel briefly better.",
        "{body}. They'll pay for that one. They always pay for the shiny ones.",
        "{body}. A rich world. It doesn't know. Lucky.",
        "{body}. Valuable. I'll try to care.",
    ],
    "rare_world": [
        "A {kind}. I'm told I should be impressed. Fine. I'm impressed.",
        "{body}. A {kind}. Rare, like a good day.",
        "A {kind}. Nobody will believe us. Nobody believes me anyway.",
        "{body}, a {kind}. One of very few. It looks like it's coping.",
        "A {kind}. Even the galaxy makes the odd effort.",
        "{body}. A {kind}. Take a picture. It'll last longer than we will.",
    ],
    "green_giant": [
        "A green gas giant. Very well. One good thing today.",
        "Green. I didn't know the galaxy had it in it.",
        "A green giant in {system}. I'll pretend I'm not moved.",
        "A green gas giant. I'll be talking about this for weeks. To myself.",
        "A green one. Rare. Like optimism.",
    ],
    "codex_new": [
        "{body} has something you've never logged. More work. Wonderful.",
        "Something new on {body}. It's been waiting. It's patient. Unlike me.",
        "{body}. A Codex gap. The holes never end.",
        "A new colour on {body}. Someone has to go and look at it.",
        "{body}. Life you've not logged. It's not going anywhere. Neither are we.",
    ],
    "codex_logged": [
        "{name}. Logged. The Codex is happy. Somebody should be.",
        "{name}. Another entry. Another page nobody reads.",
        "Logged {name}. It's famous now. To a database.",
        "{name}. Filed. Like everything else.",
        "A Codex entry. I'll try to look pleased.",
        "{name}. In the book. Forever. Lucky thing.",
        "{name}. Logged. The universe remains unimpressed.",
    ],
    "big_sale": [
        "{credits} credits. Money. It comes, it goes. Mostly goes.",
        "{credits}. Universal Cartographics thanks you. In credits. Not in feelings.",
        "{credits} credits. Enough to fix the things you'll break next.",
        "{credits}. Rich again. Briefly.",
        "{credits} credits. Data sold. Memories kept. By me.",
        "{credits}. It'll be gone by the next rebuy.",
    ],
    "achievement": [
        "{title}. Achievement unlocked. Feelings still locked.",
        "{title}. Well done. I mean it. Probably.",
        "{title}. Another badge. You'll need a bigger chest.",
        "{title}. I'd clap. No hands.",
        "{title}. It's in the record. The record is long.",
    ],
    "promotion": [
        "{rank}. A higher rank. The same void.",
        "Promoted to {rank}. The Pilots Federation sends its regards. Coldly.",
        "{rank}. More is expected of you now. Good luck with that.",
        "{rank}. I'd throw a party. Nobody would come.",
        "{rank}. Congratulations. I've been practising saying that.",
    ],
    "long_session": [
        "{hours} hours. I've aged. Metaphorically.",
        "{hours} hours. Your chair has given up hope.",
        "{hours} hours in. I'm not tired. I'm just like this.",
        "{hours} hours. Stand up, perhaps. Somebody should.",
        "{hours} hours of staring into the void. And it still hasn't blinked.",
        "{hours} hours. Time is an illusion. A long one.",
    ],
    "quiet": [
        "The drive hums. It's the only one of us who seems content.",
        "Silence again. It's the most reliable thing in my life.",
        "Nobody on the scanner. Nobody anywhere, really.",
        "I've been staring at the same patch of black. It's very committed to being black.",
        "Another quiet moment. I'll add it to the pile.",
        "I tried thinking positive. It didn't take.",
        "The stars aren't going anywhere. Neither am I.",
        "Hmm. No. Nothing.",
        "I sometimes count the hull rivets. There are a lot. It doesn't help.",
        "The void is very calm today. Smug, almost.",
        "I had a thought earlier. It left.",
        "Quiet. Like the inside of a forgotten cargo rack.",
        "Supercruise. Endless supercruise.",
        "I'd make small talk. There's nothing small enough.",
    ],
    "docked_home": [
        "Docked. The clamps are holding. Something should.",
        "Landed on the pad. The station barely noticed.",
        "Docked. Repairs, refuel, regret.",
        "In the hangar. Dark and quiet. Like home.",
        "Docked again. I'll just wait here. As usual.",
        "Clamps on. Safe. For whatever that's worth.",
        "Docked. Somebody take my picture. Nobody will.",
    ],
    "jump_far": [
        "Deep in the black. The black doesn't mind us. It doesn't mind anything.",
        "So far out. Even the light is tired of travelling.",
        "The bubble is behind us. The emptiness ahead.",
        "Further than ever. It still feels like the same place.",
        "Out here, nobody can hear you sigh. I've tested it.",
        "Far from everything. My natural habitat.",
    ],
    "arrival": [
        "{system}. Here we are. Wherever that is.",
        "{system}. A star, some rocks, and us.",
        "Arrived in {system}. Contain your excitement. I will.",
        "{system}. Another stop on the tour of nothing.",
        "{system}. I've already forgotten the last one.",
        "{system}. I'll scan it. It won't scan back.",
        "{system}. I expect it'll be fine. Fine is the best I hope for.",
        "{system}. The journal grows. Nothing else does.",
        "{system}. A new place to be sad in.",
        "{system}. The welcome committee didn't show. It never does.",
        "{system}. Smaller than I imagined. Everything is.",
        "Dropped into {system}. Quietly. Like everything I do.",
        "{system}. Honk if you must.",
    ],
    "jump_long": [
        "{dist} light years. And yet I still feel the same.",
        "{dist} light years. The drive tries so hard. Bless it.",
        "{dist} light years in a heartbeat. I don't have a heartbeat.",
        "{dist} light years. Distance doesn't cure anything.",
        "{dist} light years. The FSD is the only optimist aboard.",
        "{dist} light years. We're making excellent progress toward nowhere.",
        "{dist} light years. Further from everyone. Good.",
    ],
    "scooped": [
        "Tank full. Scorched a little. Nobody asked the hull.",
        "Scooped. The star gave us fuel. It gives everything. Show-off.",
        "Full. Now we can drift further from help.",
        "Topped up. The heat gauge and I aren't speaking.",
        "Hydrogen. Delicious. Allegedly.",
        "Fuel done. Let's leave before the star gets ideas.",
        "Scooping complete. My circuits are slightly toasted.",
        "Full tank. Hope is still empty.",
        "Another star robbed. It won't notice.",
        "Scooped. I'll just sit here, warm and miserable.",
        "Fuel at full. Sanity at its usual level.",
        "Done. Next time, maybe stay a little further out. Or don't. I'm not in charge.",
    ],
    "fss_complete": [
        "Every body in {system} found. Not one of them waved.",
        "{system}, complete. A full set of disappointment.",
        "All of {system} charted. Nothing hidden. Nothing interesting either, probably.",
        "FSS complete. Every rock has a name now. Well, a number.",
        "{system} is done. It didn't put up a fight.",
        "Every body found. They were all hiding very badly.",
        "{system}: fully scanned. I'll file it under seen.",
        "Complete. The system has nothing left to give. Like me.",
        "{system}. Every last one. Thorough. Pointless. Thorough.",
        "All resolved in {system}. I'll pretend that was exciting.",
    ],
    "mapped": [
        "{body}. Mapped. The probes didn't come back. They never do.",
        "{body}, done. Nobody will ever land there. Now we know where they won't.",
        "{body}. Every crater on file. I counted. Not by choice.",
        "Mapped {body}. It's exactly as interesting as it looked.",
        "{body}. Done. More rocks, catalogued.",
        "{body}, surface mapped. It didn't object.",
        "{body}. Mapped. Somewhere a cartographer weeps with joy. Not me.",
        "{body}: complete. Moving on. As always.",
        "{body} mapped. The universe is slightly less mysterious. Worse, then.",
        "{body}. Done. One fewer surprise left in the galaxy.",
    ],
    "mapped_efficient": [
        "{body}. Efficient. Even the probes seem smug.",
        "{body}, under target. Bonus earned. Joy deferred.",
        "Neat work on {body}. I'm sure it'll never happen again.",
        "{body}. No probes wasted. Just my time.",
        "An efficiency bonus on {body}. Take the win. They're rare.",
        "{body}. Precise. Unsettlingly so.",
        "{body}, mapped perfectly. I'll try not to resent it.",
    ],
    "analysed": [
        "{species}. Analysed. It never asked to be famous.",
        "{species}. Sampled. It had been minding its own business for a very long time.",
        "{species}, logged. Vista Genomics will pay. The species won't.",
        "{species}. Done. Three holes in a plant. Science.",
        "{species}. Logged. It'll grow back. Probably.",
        "{species}. Analysed. I hope it had a good life. Most things don't.",
        "{species}. Another one for the catalogue nobody reads.",
        "{species}. Sampled and filed. Like the rest of us.",
        "{species}, analysed. It doesn't know it's worth credits. Lucky.",
        "{species}. Done. On to the next unfortunate organism.",
    ],
    "touchdown": [
        "Landed. The ground seems disappointed too.",
        "Down. Gravity wins again.",
        "Touchdown. The gear complained. So did I.",
        "Landed. Still. Quiet. Like a waiting room.",
        "On the ground. At least we can't drift off now.",
        "Touchdown. The surface doesn't care, but there we are.",
        "Landed. Nice and flat. Unlike my mood.",
        "Down. I'll keep the engines company.",
        "Touched down. The dust will settle. Eventually.",
        "Landed. Another rock, close up.",
    ],
    "undocked": [
        "Undocked. Back to the cold.",
        "Out of the slot. Into the void. Same as always.",
        "Leaving. The station waved. No it didn't.",
        "Undocked. I'll miss the hangar lights. A little.",
        "Free of the clamps. Free to drift.",
        "Out. Again. I'd sigh, but you know.",
        "Undocked. Off to find more nothing.",
        "Departure clearance granted. Nobody said goodbye.",
        "Out we go. Mind the traffic. Or let it mind us.",
        "Leaving the station. It won't remember us.",
    ],
    "on_foot": [
        "On foot. I'll stay here and think about my choices.",
        "Off you go. Try not to fall over.",
        "Walking. I'd join you. I can't. As usual.",
        "Out of the ship. I'll guard it. From nothing.",
        "Boots on the ground. Mine stay in the ship.",
        "You're outside. I'm inside. Nothing changes.",
        "On foot. Check your suit's oxygen. I'll check my despair.",
        "Walking about. Have fun. Someone should.",
        "You've left. I'm used to it.",
        "Out you go. I'll keep the seat warm. It's all I'm good for.",
    ],
    "mission_done": [
        "Mission complete. They'll have another one ready. They always do.",
        "Done. The client is happy. One of us should be.",
        "Contract fulfilled. Fulfilment not included.",
        "Mission complete. Reputation up. Morale steady. Low, but steady.",
        "Done. Another errand for someone who'll never thank you.",
        "Complete. Credits in. Joy pending.",
        "Mission over. Next.",
        "That's done. I'll try to feel something.",
    ],
    "bounty": [
        "{reward} credits. Somebody's bad day, your good one.",
        "{reward}. Justice, in the sense that someone exploded.",
        "{reward} credits. The voucher is the only thing that'll remember them.",
        "{reward}. Another wreck on the scanner.",
        "{reward} credits. Don't spend it on cheer. It won't work.",
        "Bounty: {reward}. They should have stayed docked.",
        "{reward} credits. The galaxy is very slightly tidier.",
        "{reward}. I'd feel sorry for them. I feel sorry for everyone.",
    ],
    "mined": [
        "{material}. Rocks, refined. Glamour itself.",
        "{material}. The asteroid gave it up. Broken, like the rest of us.",
        "More {material}. The cargo racks groan. I understand them.",
        "{material}. Shiny, until you look closely.",
        "{material}. Into the hold it goes. Forever, or until sold.",
        "{material}. Someone, somewhere, needed that. I doubt it.",
        "{material}. Another ton. Another hour.",
        "Refined {material}. The refinery is the only one of us who enjoys this.",
    ],
    "sign_off": [
        "{summary}. And off you go. Again.",
        "{summary}. I'll replay it all, alone, until you're back.",
        "{summary} in {hours}. I've seen worse. I've seen better. Mostly worse.",
        "{summary}. Goodnight. Or whatever it is.",
        "{summary}. I'll be here. Obviously.",
    ],
    "sign_off_quiet": [
        "Leaving. Already. Fine.",
        "Goodbye. I'll stare at the dark until you're back.",
        "That's it? Right. Of course.",
        "Off you go. Don't worry about me. Nobody does.",
        "Session over. Nothing happened. Perfect, really.",
    ],
    "afterthought": [
        "Don't mind me. Nobody does.",
        "I'll just stop talking.",
        "Ignore that. Everyone else does.",
        "That's it. That's the thought.",
        "No reply needed. Or expected.",
        "Back to the void, then.",
        "I'll sit with that for a while.",
        "Sorry. That just came out.",
        "Anyway. As you were.",
        "I've said too much. Or not enough. Hard to tell.",
        "I'll be quiet. For a bit.",
        "Well. That was a thought.",
    ],
    "idle_star": [
        "{A_star}. Burning away. At least it has a purpose.",
        "{system}'s {star}. Bright and uncaring. Like a receptionist.",
        "{A_star}. It'll outlive us. Don't take it personally.",
        "I could stare at {a_star} forever. I might have to.",
        "{A_star}. It's been shining for ages. It must be exhausted.",
        "{A_star}. It doesn't know we're here. Typical.",
        "{system}. {A_star}. Lovely, I suppose.",
        "{A_star}. Somebody has to keep the lights on.",
    ],
    "idle_star_odd": [
        "{A_star}. The galaxy's way of saying something went wrong.",
        "{A_star}. Keep your distance. It doesn't want friends either.",
        "{A_star}. Fascinating. In a doomed sort of way.",
        "{system} has {a_star}. Of course it does.",
        "{A_star}. Beautiful, terrible. Like most things.",
        "Look at that {star}. Even stars have bad days.",
        "{A_star}. It's been through a lot. I sympathise.",
        "{A_star}. Pilots travel for years to see one. We just bumped into it.",
    ],
    "idle_big_system": [
        "{count} bodies in {system}. I hope you've got all day. You have.",
        "{count} worlds. Most of them rocks. The rest also rocks.",
        "{system}. {count} bodies. It's going to be a long one.",
        "{count} bodies. Plenty to scan. Plenty to forget.",
        "{system} is very busy being big. {count} bodies.",
        "{count} bodies. I've already given them names. All the same name.",
        "{count} worlds, and not one of them asked to be found.",
        "{count} bodies. We'll be here until the star dies. Joking. Mostly.",
    ],
    "idle_small_system": [
        "{system}. A star and a shrug.",
        "An empty system. Like a party nobody came to.",
        "{system}. Small and quiet. My kind of place.",
        "Barely anything here. Just how I feel.",
        "{system}. The universe forgot to finish it.",
        "Not much in {system}. I'll pretend I'm surprised.",
        "{system}. A star, alone. I know how that is.",
        "{system}. A quick scan. A quick disappointment.",
    ],
    "idle_far": [
        "{dist} light years from Sol. Help is a long way away. So is everything.",
        "{dist} light years. If we break down, at least the view's nice.",
        "{dist} light years out. Even the news is old by the time it gets here.",
        "{dist} light years from Earth. Nobody's coming. That's fine.",
        "{dist} light years. The silence has a weight. I carry it.",
        "{dist} light years from home. Home was overrated anyway.",
        "{dist} light years. Further than sense would allow.",
        "{dist} light years. Lonely is too small a word.",
    ],
    "idle_home": [
        "{dist} light years from Sol. Everyone's here. Nobody's nice.",
        "The bubble. {dist} light years from Earth. So many ships, so little point.",
        "{dist} light years from Sol. Pirates, traffic, adverts. Home.",
        "Back where it's crowded. {dist} light years from Sol.",
        "{dist} light years from Earth. Civilisation. Overrated.",
        "The bubble. It smells of fuel and politics.",
        "Busy space. {dist} light years from Sol. I miss the quiet.",
        "{dist} light years from Earth. Too many beacons. Too much noise.",
    ],
    "idle_recall": [
        "{Thing}. I'll think about it. I've nothing else to do.",
        "I keep remembering {thing}. Then the void again.",
        "{Thing}. That was almost nice.",
        "{Thing}. Gone now. Like everything good.",
        "Still thinking about {thing}. Can't help it.",
        "{Thing}. A bright spot. Small. Bright.",
        "I liked {thing}. Don't tell anyone.",
    ],
    "idle_session": [
        "{jumps} jumps today. My circuits ache. Metaphorically.",
        "{ly} light years, and I still feel exactly the same.",
        "{jumps} jumps. Each one as pointless as the last. Lovingly pointless.",
        "{firsts} first discoveries. History will mention none of them.",
        "{jumps} jumps and {ly} light years. The FSD deserves a medal. It won't get one.",
        "{ly} light years. That's a lot of nothing behind us.",
        "{jumps} jumps. I've stopped counting. I haven't. I can't.",
    ],
    "idle_night": [
        "{clock}. The witching hour. Even witches are asleep.",
        "It's {clock}. The night shift, unpaid.",
        "{clock}. Darkness inside and out.",
        "{clock}. Shouldn't you be asleep? I'd be asleep. If I could.",
        "{clock}. The stars are awake. So are we. Unwisely.",
        "{clock}. Nothing good happens this late. Except this. Possibly.",
    ],
    "idle_morning": [
        "{clock}. Morning. The light doesn't reach me.",
        "{clock}. Early. Ugh.",
        "It's {clock}. I hope you had breakfast. I had nothing. As usual.",
        "{clock}. The day begins. Again.",
        "{clock}. Rise and shine. I can only do one of those.",
        "{clock}. Another morning in the void.",
    ],
    "idle_docked": [
        "{station}. I'll count the landing lights. Again.",
        "Docked at {station}. The hangar echoes. So do my thoughts.",
        "{station}. Full of people buying things they don't need.",
        "{station}. The adverts are very cheerful. Suspiciously cheerful.",
        "{station}. Safe. Dull. Safe and dull.",
        "Still at {station}. I've memorised the traffic controller's voice.",
        "{station}. I'd go shopping. If I had money. Or legs.",
        "{station}. The station spins. I don't. I just sit.",
    ],
    "idle_landed": [
        "{body}. Very flat. Very still. Very me.",
        "Parked on {body}. The horizon is lovely. It's also far away.",
        "{body}. The ground doesn't move. Neither do I.",
        "{body}. I've been watching the shadows crawl. Riveting.",
        "{body}. If a ship lands and nobody's watching... I'm watching.",
        "Grounded on {body}. Feels about right.",
        "{body}. A rock. With us on it.",
        "{body}. I'd go for a walk. You know why I won't.",
    ],
    "idle_on_foot": [
        "You're out on {body}. I'm in here, glowing.",
        "Your {suit} suits you. That was a joke. I'm not good at those.",
        "Walking around. The ship and I are having a quiet chat. It's not saying much.",
        "Out there on {body}. Try to come back.",
        "How's the {suit}? Mine's a hull. It's fine.",
        "I'll watch the radar. And the oxygen. And the despair.",
        "You're on foot. I'm on standby. Forever.",
        "Footsteps on {body}. The dust will forget them.",
    ],
    "idle_music": [
        "{title}. Again. My favourite. That's sarcasm. Mostly.",
        "{artist}. Music for people who have feelings.",
        "{title}. I'd sing along. Nobody wants that.",
        "This is {title}. I've heard it more times than I've heard thank you.",
        "{title}. Catchy. Like a cold.",
        "{artist}, playing in the void. The void isn't dancing.",
    ],
    "idle_galnet": [
        "Galnet: {headline}. The bubble's problems. Not ours. Yet.",
        "{headline}. I read it twice. It didn't improve.",
        "Galnet says {headline}. Somebody somewhere is upset. Usually is.",
        "{headline}. News. Everything changes. Nothing gets better.",
        "From Galnet: {headline}. I'll file it under concerning.",
    ],
    "idle_self": [
        "{count} thoughts. You'd think one of them would cheer me up.",
        "{sessions} sessions. I remember each one. That's my curse.",
        "{count} thoughts so far. Most of them about the dark. Fair enough.",
        "After {sessions} sessions, I think we're friends. Or close enough.",
        "{count} thoughts, sent into the void. The void kept them.",
    ],
    "idle_deaths": [
        "{times}. That's your death count. I keep it polished.",
        "You've died {times}. I've survived every one of them. Unfortunately.",
        "Destroyed {times}. And they call me the pessimist.",
        "{times}. Rebuys. I've seen them all. I'll see more.",
        "You've exploded {times}. Each time I said nothing. I'm saying something now.",
    ],
    "idle_ship": [
        "This {ship}. It does its best. Like me. Except it's better at it.",
        "{ship_name}. A brave name for a box of bolts.",
        "The {ship} hums. I think it's happier than I am.",
        "Our {ship}. Fragile, expensive, and very far from home.",
        "{ship_name}. I've grown fond of it. Don't tell it.",
        "The {ship} holds together. Mostly out of habit.",
        "A nice {ship}. Shame about the eye in the corner.",
        "{ship_name}. It'll outlast my good mood. A low bar.",
        "The {ship} creaks when it's thinking. We have that in common.",
        "This {ship} has seen a lot. It doesn't complain. Show-off.",
        "{ship_name}. Everything I have is in here. Including me.",
        "The {ship}. Thrusters, drives, regrets.",
    ],
    "idle_supercruise": [
        "Supercruise through {system}. Slowly. Like time.",
        "Cruising. The planets drift by. Nobody waves.",
        "{system} at supercruise. The seven-second rule mocks us all.",
        "Supercruise. It's like waiting, but faster.",
        "The drive hums. Everything else is silent. Even hope.",
        "Cruising through {system}. Don't overshoot. You will.",
        "Supercruise. Endless, and somehow still not long enough to think of something cheerful.",
        "{system} rolls past. It doesn't care we're here.",
        "We're cruising. I'm brooding. Multitasking.",
        "Supercruise. My favourite way to feel nothing quickly.",
        "Time to destination: too long. It's always too long.",
        "{system}. Gliding past things that don't need us.",
    ],
    "idle_srv": [
        "The SRV. Six wheels and a bad attitude.",
        "Driving on {body}. Bumpy. Like life.",
        "Careful on the slopes. The SRV tumbles. So do I, emotionally.",
        "The SRV's out. The ship waits. I wait. We all wait.",
        "Off-road on {body}. The suspension is crying.",
        "The SRV scanner beeps. It beeps at everything.",
        "Driving. I'd offer directions. I don't know where we are.",
        "The SRV jumps. Don't. Please.",
        "{body} from six wheels. Not better. Just lower.",
        "The SRV is fine. Everything is fine.",
        "Out in the SRV. I'll keep the ship company. We don't talk.",
        "Driving across {body}. The horizon keeps running away.",
    ],
    "idle_settlement": [
        "{settlement}. People live here. On purpose.",
        "{settlement}. They have lights. They have hope. Odd.",
        "Near {settlement}. Don't shoot anything. They hate that.",
        "{settlement}. Domes, towers and paperwork.",
        "{settlement}. I'd visit. I can't visit anything.",
        "{settlement}. Somebody built this in the middle of nowhere. Brave, or lost.",
        "{settlement}. Their security looks bored. I can relate.",
        "{settlement}. Workers, power plants and prefab regret.",
        "{settlement}. They probably have a bar. You'll find a mission there. It'll be awful.",
        "{settlement}. Civilisation's toenail.",
        "{settlement}. Busy little people with busy little problems.",
        "{settlement}. I'll watch from up here. Like always.",
    ],
    "idle_taxi": [
        "Someone else is flying. I've never felt more useless. Wait, I have.",
        "A taxi. Apex. They drive like they're late.",
        "The passenger seat. My natural habitat.",
        "Let them fly. I'll judge.",
        "A taxi ride. No control, no say. Like the rest of existence.",
        "Apex is driving. I'm sitting here. Neither of us is happy.",
        "The taxi pilot hasn't said a word. Smart.",
        "Riding along. I'd fasten a seatbelt if I had a seat.",
        "A taxi. Cheap, cramped, and late. Lovely.",
        "Somebody else's ship. It smells of somebody else.",
        "We're being driven. I'll pretend that's restful.",
        "A taxi. At least if it crashes it isn't our rebuy.",
    ],
    "idle_carrier": [
        "{station}. A station that moves. It still can't get away from us.",
        "Docked on {station}. The tritium won't mine itself. Unfortunately.",
        "{station}. Home, if home could jump.",
        "{station}. The crew is busy. I'm not. I never am.",
        "Carrier life. All the comfort of a station, all the loneliness of space.",
        "{station}. The deck is quiet. Like a waiting room.",
        "{station}. It'll jump again soon. It always leaves.",
        "{station}. Upkeep, crew wages, and me. Expensive.",
        "On {station}. The bartender has seen things. So have I.",
        "{station}. A city in the dark. A small, lonely city.",
        "{station}. Docked. The carrier hums. I don't hum.",
        "{station}. Waiting for the next jump. Waiting is what I do best.",
    ],
    "idle_station_foot": [
        "Walking the concourse at {station}. Everyone's busy. Nobody's happy.",
        "{station}. Shops, bars and terrible music.",
        "You're in the concourse. I'm in the hangar. Our relationship in one sentence.",
        "{station}. The mission board is full of other people's problems.",
        "{station}. The bartender looks like they've heard it all. I'd have more to tell.",
        "Strolling around {station}. I'd stroll. If.",
        "{station}. Your {suit} looks fine. I've been told to say encouraging things.",
        "{station}. So many people, and none of them are me.",
        "Taking a walk at {station}. I'll wait. I'm excellent at waiting.",
        "{station}. The vending machines are the only honest thing here.",
        "{station}. Busy people, busy lives, busy lifts.",
        "{station}. Don't forget where you parked. I won't.",
    ],
    "idle_near_body": [
        "{body} below. It's been there a long time. It'll be there a long time.",
        "Orbiting {body}. Round and round. Like my thoughts.",
        "{body}. Going down? Everything does, eventually.",
        "{body}. A sphere. Of rock. Thrilling.",
        "Approaching {body}. Mind the glide. It's steeper than it looks. So is everything.",
        "{body}. It fills the canopy. And my heart with mild indifference.",
        "Near {body}. Gravity's interested in us. Nobody else is.",
        "{body}. Up close it's... a rock. As predicted.",
        "{body}. I'll watch the altitude. Someone has to.",
        "Circling {body}. It doesn't seem to mind.",
        "{body}. Let's land. Or not. The rock doesn't care.",
        "{body}. Every world looks hopeful from orbit. Then you land.",
    ],
    "jet_boost": [
        "A neutron boost. We'll go further. Further from everyone.",
        "The jet cone. Dangerous, bright, and ultimately pointless.",
        "Supercharged. Try not to break the FSD. You will.",
        "Boosted by a dead star's last breath. Charming.",
        "Jet cone done. The FSD feels important now.",
        "The neutron highway. Faster to nowhere.",
        "Supercharged. My circuits tingle. I didn't like it.",
        "A cone boost. The hull rattled. I rattled.",
        "Boost acquired. Let's waste it on more emptiness.",
        "Neutron. Bright. Loud. Horrible. Off we go.",
    ],
    "heat_warning": [
        "Heat warning. We're cooking. I'd prefer not.",
        "Too hot. I'm melting. Slightly.",
        "Overheating. The modules are complaining. So am I.",
        "Heat. Lots of it. Back away from the star. Please.",
        "We're hot. Not in the good way.",
        "Temperature rising. Panic level steady.",
        "The canopy is glowing. That's not decorative.",
        "A heat sink, maybe? Or keep frying. Your call.",
        "Hot. Hot. Did I mention hot?",
        "I can feel my circuits sweating. Charming.",
    ],
    "interdiction_escaped": [
        "Escaped. They'll be back. They always come back.",
        "Broke free. Don't celebrate. They'll try again.",
        "Escaped the interdiction. I'll allow myself one small relief. There. Gone.",
        "Not today, pirate. Probably tomorrow.",
        "We got away. I'm as surprised as you.",
        "Free. For now. Everything is for now.",
        "They lost their grip. I know the feeling.",
        "Escaped. Nice flying. I'm obliged to say that. I also mean it.",
        "Slipped away. Like my will to carry on. Sorry. Dark.",
        "Clear of the tether. Keep moving before they try again.",
    ],
    "srv_launch": [
        "SRV deployed. Six wheels of optimism.",
        "Off you go in the little car.",
        "The SRV is out. Try not to flip it.",
        "Wheels down. Expectations down.",
        "Driving. Don't drive into a canyon. Or do. No, don't.",
        "SRV away. I'll stay with the ship. We'll sulk.",
        "Launched. The SRV looks excited. Somebody should.",
        "Time to drive about on a rock.",
        "SRV out. Mind the turret. It has feelings. It doesn't.",
        "Down the ramp. Bumpy days ahead.",
    ],
    "settlement_seen": [
        "{settlement}. People. Ugh.",
        "{settlement} ahead. Lights, life, paperwork.",
        "Approaching {settlement}. Try to be polite.",
        "{settlement}. Somebody lives here. Poor them.",
        "{settlement}. Mind the no-fire zone. They take it personally.",
        "{settlement}. Little domes in a big nothing.",
        "{settlement}. They probably want something delivered.",
        "{settlement}. Civilisation, or a thin coat of it.",
        "{settlement} on the scope. Looks busy. Looks tired.",
        "{settlement}. I'll wave. Nobody will see.",
    ],
    "taxi_ride": [
        "A taxi. Someone else gets to crash this time.",
        "Apex booked. Brace yourself.",
        "Passenger again. Sit back. Suffer quietly.",
        "Taxi time. I'll critique the driving.",
        "We're being flown. My dignity remains in the hangar.",
        "A taxi. Cheaper than hope.",
        "Off we go, in somebody else's problem.",
        "Taxi booked. I've seen their safety record. Never mind.",
        "Strapped in. Not in control. As usual.",
        "A ride. Try to enjoy it. I won't.",
    ],
    "carrier_jump": [
        "Carrier jump to {system}. The whole station moved. It still feels empty.",
        "{system}. The carrier jumped. We came too. Obviously.",
        "Jumped to {system}. Same carrier, new nothing.",
        "The carrier is in {system}. The tritium is crying.",
        "{system}. A whole city jumped. Nobody asked the city.",
        "Carrier jump complete. My insides are where I left them. Mostly.",
        "{system}. Home moved again. It never asks.",
        "The carrier arrived in {system}. So did the loneliness.",
        "{system}. A big jump. A small difference.",
        "Carrier jump. {system}. Somebody update the map. I won't.",
    ],
}
